#!/bin/sh
#
# script to run the load test over and over again until a failure occurs.
# for a clean shutdown create a file called stop in the current directory.
#

while true
do
	date
	./load
	if [ $? -ne 0 ]
	then
		exit
	fi
	if [ -f stop ]
	then
		exit
	fi
done
