#	copyright	"%c%"

#ident	"@(#)find:find.mk	1.10.11.1"
#ident  "$Header$"

#	Makefile for find

include $(CMDRULES)

LOCALDEF = -D_FILE_OFFSET_BITS=64

INSDIR = $(USRBIN)
OWN = bin
GRP = bin

INCSYS = $(INC)

LDLIBS =

#top#
# Generated by makefile 1.47

MAKEFILE = find.mk


MAINS = find

OBJECTS =  find.o

SOURCES =  find.c

all:		$(MAINS)

find:		find.o 
	$(CC) -o $@ find.o $(LDFLAGS) $(LDLIBS) $(PERFLIBS)


find.o:		 $(INC)/stdio.h $(INC)/errno.h $(INC)/pwd.h \
		 $(INC)/grp.h $(INCSYS)/sys/types.h $(INCSYS)/sys/stat.h \
		 $(INCSYS)/sys/param.h $(INC)/ftw.h $(INC)/limits.h \
		 $(INC)/unistd.h $(INC)/stdlib.h $(INC)/locale.h \
		 $(INCSYS)/sys/mac.h $(INC)/ctype.h $(INC)/pfmt.h \
		 $(INC)/errno.h $(INC)/string.h

GLOBALINCS = $(INC)/stdio.h $(INC)/errno.h $(INC)/pwd.h \
	$(INC)/grp.h $(INCSYS)/sys/types.h $(INCSYS)/sys/stat.h \
	$(INCSYS)/sys/param.h $(INC)/ftw.h $(INC)/limits.h \
	$(INC)/unistd.h $(INC)/stdlib.h $(INC)/locale.h \
	$(INCSYS)/sys/mac.h $(INC)/ctype.h $(INC)/pfmt.h \
	$(INC)/errno.h $(INC)/string.h

install: all
	$(INS) -f $(INSDIR) -m 0555 -u $(OWN) -g $(GRP) $(MAINS)

clean:
	rm -f $(OBJECTS)

clobber: clean
	rm -f $(MAINS)

lintit:
	$(LINT) $(LINTFLAGS) *.c

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

size: all
	$(SIZE) $(MAINS)

strip: all
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(INSDIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(INSDIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
