#!/usr/bin/ksh
#ident	"@(#)dsmaps	15.1"

pkgdir=$1
shift

cd $PROTO/stage
find hbaflop -print | cpio -dump $pkgdir
cd $pkgdir

{
	find hbaflop -print
	find .extra.d -print
	for i
	do
		echo $i/pkginfo
		echo $i/pkgmap
		[ -f $i/setinfo ] && echo $i/setinfo
	done
} | cpioout
