#ident	"@(#)ksh93:include/ast/debug.h	1.1"
/***************************************************************
*                                                              *
*                      AT&T - PROPRIETARY                      *
*                                                              *
*         THIS IS PROPRIETARY SOURCE CODE LICENSED BY          *
*                          AT&T CORP.                          *
*                                                              *
*                Copyright (c) 1995 AT&T Corp.                 *
*                     All Rights Reserved                      *
*                                                              *
*           This software is licensed by AT&T Corp.            *
*       under the terms and conditions of the license in       *
*       http://www.research.att.com/orgs/ssr/book/reuse        *
*                                                              *
*               This software was created by the               *
*           Software Engineering Research Department           *
*                    AT&T Bell Laboratories                    *
*                                                              *
*               For further information contact                *
*                     gsf@research.att.com                     *
*                                                              *
***************************************************************/

/* : : generated by proto : : */
                  
/*
 * common ast debug definitions
 * include after the ast headers
 */

#ifndef _DEBUG_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif

#define _DEBUG_H

#include <ast.h>
#include <error.h>

#if DEBUG || _TRACE_
#define debug(x)	x
#define libmessage(x)	do if (error_info.trace < 0) { liberror x; } while (0)
#define message(x)	do if (error_info.trace < 0) { error x; } while (0)
#else
#define debug(x)
#define libmessage(x)
#define message(x)
#endif

extern __MANGLE__ void		systrace __PROTO__((const char*));

#endif
