#ident	"@(#)ksh93:include/ast/namval.h	1.1"
/***************************************************************
*                                                              *
*                      AT&T - PROPRIETARY                      *
*                                                              *
*         THIS IS PROPRIETARY SOURCE CODE LICENSED BY          *
*                          AT&T CORP.                          *
*                                                              *
*                Copyright (c) 1995 AT&T Corp.                 *
*                     All Rights Reserved                      *
*                                                              *
*           This software is licensed by AT&T Corp.            *
*       under the terms and conditions of the license in       *
*       http://www.research.att.com/orgs/ssr/book/reuse        *
*                                                              *
*               This software was created by the               *
*           Software Engineering Research Department           *
*                    AT&T Bell Laboratories                    *
*                                                              *
*               For further information contact                *
*                     gsf@research.att.com                     *
*                                                              *
***************************************************************/

/* : : generated by proto : : */
                  
/*
 * Glenn Fowler
 * AT&T Bell Laboratories
 *
 * common name-value struct support
 */

#ifndef _NAMVAL_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif

#define _NAMVAL_H

typedef struct
{
	char*		name;
	int		value;
#ifdef _NAMVAL_PRIVATE_
	_NAMVAL_PRIVATE_
#endif
} Namval_t;

#endif
