#ident	"@(#)ksh93:include/ast/sfdisc.h	1.1"
/***************************************************************
*                                                              *
*                      AT&T - PROPRIETARY                      *
*                                                              *
*         THIS IS PROPRIETARY SOURCE CODE LICENSED BY          *
*                          AT&T CORP.                          *
*                                                              *
*                Copyright (c) 1995 AT&T Corp.                 *
*                     All Rights Reserved                      *
*                                                              *
*           This software is licensed by AT&T Corp.            *
*       under the terms and conditions of the license in       *
*       http://www.research.att.com/orgs/ssr/book/reuse        *
*                                                              *
*               This software was created by the               *
*           Software Engineering Research Department           *
*                    AT&T Bell Laboratories                    *
*                                                              *
*               For further information contact                *
*                     gsf@research.att.com                     *
*                                                              *
***************************************************************/

/* : : generated by proto : : */
                  
/*
 * AT&T Bell Laboratories
 *
 * sfio discipline interface definitions
 */

#ifndef _SFDISC_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif

#define _SFDISC_H

#include <ast.h>

/*
 * %(...) printf support
 */

typedef int (*Sf_key_lookup_t) __PROTO__((__V_*, const char*, const char*, int, char**, long*));
typedef char* (*Sf_key_convert_t) __PROTO__((__V_*, const char*, const char*, int, char*, long));

extern __MANGLE__ int		sfkeyprintf __PROTO__((Sfio_t*, __V_*, const char*, Sf_key_lookup_t, Sf_key_convert_t));

/*
 * slow io exception discipline
 */

extern __MANGLE__ int		sfslowio __PROTO__((Sfio_t*));

#endif
