#ident	"@(#)ksh93:include/ast/swap.h	1.1"
/***************************************************************
*                                                              *
*                      AT&T - PROPRIETARY                      *
*                                                              *
*         THIS IS PROPRIETARY SOURCE CODE LICENSED BY          *
*                          AT&T CORP.                          *
*                                                              *
*                Copyright (c) 1995 AT&T Corp.                 *
*                     All Rights Reserved                      *
*                                                              *
*           This software is licensed by AT&T Corp.            *
*       under the terms and conditions of the license in       *
*       http://www.research.att.com/orgs/ssr/book/reuse        *
*                                                              *
*               This software was created by the               *
*           Software Engineering Research Department           *
*                    AT&T Bell Laboratories                    *
*                                                              *
*               For further information contact                *
*                     gsf@research.att.com                     *
*                                                              *
***************************************************************/

/* : : generated by proto : : */
                  
/*
 * Glenn Fowler
 * AT&T Bell Laboratories
 *
 * integral representation conversion support definitions
 * supports sizeof(integral_type)<=sizeof(int_max)
 */

#ifndef _SWAP_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif

#define _SWAP_H

#include <int.h>

#define SWAP_MAX	8

extern __MANGLE__ __V_*		swapmem __PROTO__((int, const __V_*, __V_*, size_t));
extern __MANGLE__ int_max		swapget __PROTO__((int, const __V_*, int));
extern __MANGLE__ __V_*		swapput __PROTO__((int, __V_*, int, int_max));
extern __MANGLE__ int		swapop __PROTO__((const __V_*, const __V_*, int));

#endif
