#ident	"@(#)ksh93:include/ast/tok.h	1.1"
/***************************************************************
*                                                              *
*                      AT&T - PROPRIETARY                      *
*                                                              *
*         THIS IS PROPRIETARY SOURCE CODE LICENSED BY          *
*                          AT&T CORP.                          *
*                                                              *
*                Copyright (c) 1995 AT&T Corp.                 *
*                     All Rights Reserved                      *
*                                                              *
*           This software is licensed by AT&T Corp.            *
*       under the terms and conditions of the license in       *
*       http://www.research.att.com/orgs/ssr/book/reuse        *
*                                                              *
*               This software was created by the               *
*           Software Engineering Research Department           *
*                    AT&T Bell Laboratories                    *
*                                                              *
*               For further information contact                *
*                     gsf@research.att.com                     *
*                                                              *
***************************************************************/

/* : : generated by proto : : */
                  
/*
 * Glenn Fowler
 * AT&T Bell Laboratories
 *
 * token stream interface definitions
 */

#ifndef _TOK_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif

#define _TOK_H

#include <ast.h>

extern __MANGLE__ Sfio_t*		tokline __PROTO__((const char*, int, int*));
extern __MANGLE__ int		tokscan __PROTO__((char*, char**, const char*, ...));
extern __MANGLE__ char*		tokopen __PROTO__((char*, int));
extern __MANGLE__ void		tokclose __PROTO__((char*));
extern __MANGLE__ char*		tokread __PROTO__((char*));

#endif
