#ident	"@(#)ksh93:include/ast/vecargs.h	1.1"
/***************************************************************
*                                                              *
*                      AT&T - PROPRIETARY                      *
*                                                              *
*         THIS IS PROPRIETARY SOURCE CODE LICENSED BY          *
*                          AT&T CORP.                          *
*                                                              *
*                Copyright (c) 1995 AT&T Corp.                 *
*                     All Rights Reserved                      *
*                                                              *
*           This software is licensed by AT&T Corp.            *
*       under the terms and conditions of the license in       *
*       http://www.research.att.com/orgs/ssr/book/reuse        *
*                                                              *
*               This software was created by the               *
*           Software Engineering Research Department           *
*                    AT&T Bell Laboratories                    *
*                                                              *
*               For further information contact                *
*                     gsf@research.att.com                     *
*                                                              *
***************************************************************/

/* : : generated by proto : : */
                  
/*
 * Glenn Fowler
 * AT&T Bell Laboratories
 *
 * vector argument interface definitions
 */

#ifndef _VECARGS_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif

#define _VECARGS_H

extern __MANGLE__ int		vecargs __PROTO__((char**, int*, char***));
extern __MANGLE__ char**		vecfile __PROTO__((const char*));
extern __MANGLE__ void		vecfree __PROTO__((char**, int));
extern __MANGLE__ char**		vecload __PROTO__((char*));
extern __MANGLE__ char**		vecstring __PROTO__((const char*));

#endif
