#ifndef NOIDENT
#pragma ident	"@(#)dtadmin:internet/inetMsg.h	1.36.2.1"
#endif

#define FS    "\001"
#define TXT_OK		"inet:1" FS	"OK"
#define TXT_Reset	"inet:2" FS	"Reset"
#define TXT_Cancel	"inet:3" FS	"Cancel"
#define TXT_Help	"inet:4" FS	"Help"
#define TXT_dot		"inet:5" FS	"."
#define TXT_Apply	"inet:6" FS	"Apply"
#define TXT_Copy	"inet:7" FS	"Copy"
#define TXT_Search	"inet:8" FS	"Search"
#define TXT_Add		"inet:9" FS	"Add"

#define TXT_sla_status	"inet:10" FS	"Enter the system name"
#define TXT_ans_status	"inet:11" FS	"Enter new system..."

#define TXT_appName	"inet:12" FS	"Internet Setup"
#define TXT_etcHostView "inet:13" FS	"Internet Setup - Systems List"
#define TXT_dnsView 	"inet:14" FS	"Internet Setup - Domain Listing"
#define TXT_propView	"inet:15" FS	"Internet Setup: System Properties"
#define TXT_newView	"inet:16" FS	"Internet Setup: Add New System"
#define TXT_configView	"inet:17" FS	"Internet Setup: Configure Local System"
#define TXT_copyView	"inet:18" FS	"Internet Setup: Copy To Folder"
#define TXT_slaView	"inet:19" FS	"Internet Setup: Set Local Access"
#define TXT_uucpView	"inet:20" FS	"Internet Setup: UUCP Transfer Setup"
#define TXT_nsaView	"inet:21" FS	"Internet Setup: Name Server Access"
#define TXT_nisView	"inet:22" FS	"Internet Setup: NIS Access"
#define TXT_routeView	"inet:23" FS	"Internet Setup: Routing Setup"
#define TXT_info	"inet:24" FS	"Internet Setup: Information"

#define TXT_inet_addr	"inet:25" FS	"Network Address:"
#define TXT_LDN		"inet:26" FS	"Domain Name:"
#define TXT_name_server	"inet:27" FS	"Name Server:"
#define TXT_system_name "inet:28" FS	"System Name:"
#define TXT_set_access	"inet:29" FS	"Set Access Rights For:"
#define TXT_personal	"inet:30" FS	"Personal Account Only"
#define TXT_EntireSystem "inet:31" FS	"Entire System"
#define TXT_PersonalAcc "inet:32" FS	"Personal Account Only"
#define TXT_add		"inet:33" FS	"Add"
#define TXT_mod		"inet:34" FS	"Modify"
#define TXT_delete	"inet:35" FS	"Delete"
#define TXT_Login	"inet:36" FS	"Login ID:"
#define TXT_Allow	"inet:37" FS	"Allowed Users"
#define TXT_NoOne	"inet:38" FS	"No One"
#define TXT_All		"inet:39" FS	"All Users"
#define TXT_Self	"inet:40" FS	"Self"
#define TXT_aliases	"inet:41" FS	"Aliases:"
#define TXT_ex_aliases	"inet:42" FS	"Existing Aliases"
#define TXT_Specific	"inet:43" FS	"Specific Users"
#define TXT_comment	"inet:44" FS	"Comment:"
#define TXT_getAddr	"inet:45" FS	"Get Address"
#define TXT_copy	"inet:46" FS	"Copy:"
#define TXT_to		"inet:47" FS	"To:"
#define TXT_as		"inet:48" FS	"As:"

#define TXT_etcLabel	"inet:49" FS	"Systems defined in Local Systems List (etc/hosts)"
#define TXT_domain	"inet:50" FS	"Domain:"
#define TXT_domainBut	"inet:51" FS	"Update Listing"
#define TXT_domainLabel "inet:52" FS	"Domains & Systems For:"
#define TXT_domains	"inet:53" FS	"Domains"
#define TXT_systems	"inet:54" FS	"Systems"

#define TXT_slate	"inet:55" FS	"slate"
#define TXT_path	"inet:56" FS	"/home/hclee"
#define TXT_folder	"inet:57" FS	"Folders in <curfolder>:"
#define TXT_servers	"inet:58" FS	"Exisiting DNS Servers"
#define TXT_nis_servers	"inet:59" FS	"NIS Servers"

#define TXT_uucpLabel	"inet:60" FS	"The UNIX System UUCP Facility is used to send and \nreceive mail and file transfers.\n\nEnter the name of the system for which you \nwant to accept or reject UUCP mail / file transfers.\n"
#define TXT_userlabel	"inet:61" FS	"Users on %s That May Access Your System:"

#define TXT_showOptions "inet:62" FS	"Show Other Options"
#define TXT_nisServer	"inet:63" FS	"NIS Server:"
#define TXT_nisDomain	"inet:64" FS	"NIS Domain Name:"
#define TXT_network_id	"inet:65" FS	"Network Id:"
#define TXT_host_id	"inet:66" FS	"Host Id:"
#define TXT_address	"inet:67" FS	"Address"
#define TXT_name	"inet:68" FS	"Name"

#define TXT_subnetMask	"inet:69" FS    "Subnet Mask"
#define TXT_subnetType	"inet:70" FS    "Subnet Type:"
#define TXT_classA	"inet:71" FS    "Class A"
#define TXT_classB	"inet:72" FS    "Class B"
#define TXT_classC	"inet:73" FS    "Class C"
#define TXT_other	"inet:74" FS    "Other"
#define TXT_mask	"inet:75" FS    "Mask"
#define TXT_networkRoute	"inet:76" FS    "Network Routing"
#define TXT_defRouter	"inet:77" FS    "Default Router:"
#define TXT_updateRoute	"inet:78" FS    "Update Routing Tables Using Broadcasted Info        "

#define TXT_cur_status	"inet:79" FS	"Current status:"
#define TXT_accepted	"inet:80" FS	"Accepting from <%s>"
#define TXT_rejected	"inet:81" FS	"Rejecting from <%s>"
#define TXT_inUucpFile	"inet:82" FS	"The entry <%s> already in uucp file"
#define TXT_notInUucpFile	"inet:83" FS	"The entry <%s> does not exist in uucp file"

/* ====== New q4 messages ====== */

#define TXT_tmpSys	"inet:84" FS    "slate      "
#define TXT_accept	"inet:85" FS    "Accept"

#define ERR_routeSingle	"inet:86" FS "The following error was detected.\n"
#define ERR_routeMulti	"inet:87" FS "The following errors were detected.\n"
#define ERR_routeMsg1	"inet:88" FS "detected.\n"
#define ERR_routeBadName "inet:89" FS "\n-The Router you specified does not appear to exist."
#define ERR_routeBadAddr "inet:90" FS "\n-You must enter a complete Network Address"
#define ERR_routeBadNetmask "inet:100" FS "\n-Incomplete or invalid Netmask for class \"Other\""
#define ERR_routeMsg2	"inet:101" FS "\n\nClick on \"OK\" to return to the Routing Setup window."
#define WARN_routeMsg1	"inet:102" FS "The Default Router and/or address could not be located in the Network Address\ndatabases. Please be sure to add and entry for it when your are done."
#define TXT_routeOkMsg	"inet:103" FS "The routing changes you specified have been saved to disk.\nYou must now reboot your machine in order for the changes to take effect."
#define TXT_routeMask	"inet:104" FS "Mask: 0x"
#define ERR_routeInit	"inet:105" FS "Note: A fatal error was detected during Routing Setup initialization.\nPlease contact your system administrator."

#define TXT_nisServers	"inet:106" FS "Existing NIS Servers"

#define ERR_nisErr1	"inet:107" FS "Could not initialize NIS database. Select \"Cancel\" from\nthe NIS Access window and contact your system administrator"

#define TXT_deleteInfo	"inet:108" FS	"Are you sure want to delete this entry?"
#define TXT_insertInfo	"inet:109" FS	"Do you want this entry to be the primary DNS Server?"
#define TXT_invalidDomainName	"inet:110" FS	"Invalid extension for the domain name: '.com' will be used."

#define ERR_cantGetAddr "inet:111" FS	"An address for %s cannot be found"
#define ERR_memory	"inet:112" FS	"Memory allocation problem, check system."
#define ERR_cantOpenEtcFile 	"inet:113" FS	"Cannot open /etc/hosts file"
#define ERR_cantOpenFile 	"inet:114" FS	"Cannot open %s file"
#define ERR_cantWriteFile 	"inet:115" FS	"Cannot write to %s file"

#define INFO_systemNeed "inet:116" FS	"You must enter a System Name."
#define INFO_addrNeed 	"inet:117" FS	"You must enter a Network Address."
#define INFO_sameNameNoQuery	"inet:118" FS	"You did not enter a new Domain Name"
#define INFO_inEtcFile	"inet:119" FS	"An entry with this name and address already exists in the /etc/hosts file"
#define INFO_inUucpFile	"inet:120" FS	"Entry already in UUCP file"
#define INFO_cantFindEntry	"inet:121" FS	"Cannot find %s"

#define INFO_setupNet	"inet:122" FS	"Setting up the network... Please wait..."
#define INFO_setupOK	"inet:123" FS	"Network has been initialized"
#define INFO_installDone	"inet:124" FS	"\"%s\" copied."

#define TXT_nsa_status	"inet:125" FS	"Enter the name of your organization's Domain."
#define ERR_cantGetPasswd       "inet:126" FS     "Could not retrieve your login ID.  Cannot configure local access for 'Self'."
#define ERR_cantAccDomain	"inet:127" FS	"Cannot set access rights on a domain"
#define ERR_cantConfLocalSys	"inet:128" FS	"Cannot configure local system"
#define TXT_iconName		"inet:129" FS	"Internet_Setup"
#define ERR_sameHost		"inet:130" FS	"Cannot copy an icon for your own system."
#define ERR_noNodeDir		"inet:131" FS	"Could not create .node directory."
#define ERR_noAccessNodeDir	"inet:132" FS	"Could not access the .node directory."
#define ERR_pathDeny		"inet:133" FS	"\"%s\" does not exist or permission to access is denied!"
#define ERR_installFailed	"inet:134" FS	"Copying of \"%s\" failed!"
#define ERR_noPriv		"inet:135" FS	"The system has not yet been configured for networking and you do not have the appropriate permission to do this."
#define ERR_noTCP		"inet:136" FS	"TCP/IP networking is not running. You may need to reboot your system."
#define ERR_listenerFail	"inet:137" FS	"Attempt to configure the TCP/IP network listener on this machine failed. You should reboot your system."
#define ERR_uucpFail		"inet:138" FS	"Attempt to configure UUCP through TCP/IP failed.  See the log file (%s) for details."

#define ERR_noSetup		"inet:139" FS	"Cannot display Domain Listing nor can the /etc/hosts file be read successfully.  Files may be corrupted!"

#define ERR_noNameServer	"inet:140" FS	"No Name Server available for domain %s."	
#define ERR_cantWait		"inet:141" FS	"Internal Error: Can't wait the child"
#define ERR_killBySignal	"inet:142" FS	"Lookup process terminated."
#define ERR_unkown		"inet:143" FS	"Lookup terminated for unknown reason"	
#define ERR_cantFork	"inet:144" FS	"Internal Error: Can't fork process"

#define WARN_noNetConfig	"inet:145" FS	"Although the name server records have been saved to resolv.conf,\n the system will nevertheless be unable to access a Name Server due to a missing\n or incomplete /etc/netconfig file.\n An administrator would need to be contacted to fix the problem."

#define INFO_copySystem "inet:146" FS	"Are you sure want to copy this entry to the /etc/hosts file?"

#define MENU_sla	"inet:147" FS "Set Local Access..."
#define MENU_uucp	"inet:148" FS "UUCP Transfer Setup..."
#define MENU_dns	"inet:149" FS "DNS Access..."
#define MENU_nis	"inet:150" FS "NIS Access..."
#define MENU_route	"inet:151" FS "Routing Setup..."
#define MENU_exit	"inet:152" FS "Exit"
#define MENU_sysNew	"inet:153" FS "New..."
#define MENU_sysCTF	"inet:154" FS "Copy To Folder..."
#define MENU_sysCTSL	"inet:155" FS "Copy To Systems List"
#define MENU_sysDel	"inet:156" FS "Delete"
#define MENU_sysProp	"inet:157" FS "Properties..."
#define MENU_viewSL	"inet:158" FS "Systems List"
#define MENU_viewDL	"inet:159" FS "Domain Listing"
#define MENU_viewStL	"inet:160" FS "Shift To Left"
#define MENU_viewStR	"inet:161" FS "Shift To Right"
#define MENU_findSearch	"inet:162" FS "Search..."
#define MENU_findFirst	"inet:163" FS "First"
#define MENU_findLast	"inet:164" FS "Last"
#define MENU_helpIS	"inet:165" FS "Internet Setup..."
#define MENU_helpTOC	"inet:166" FS "Table Of Contents..."
#define MENU_helpHD	"inet:167" FS "Help Desk..."
#define MENUBAR_actions	"inet:168" FS "Actions"
#define MENUBAR_system	"inet:169" FS "System"
#define MENUBAR_view	"inet:170" FS "View"
#define MENUBAR_find	"inet:171" FS "Find"
#define MENUBAR_help	"inet:172" FS "Help"
#define MNE_A		"inet:173" FS "A"
#define MNE_C		"inet:174" FS "C"
#define MNE_D		"inet:175" FS "D"
#define MNE_F		"inet:176" FS "F"
#define MNE_H		"inet:177" FS "H"
#define MNE_I		"inet:178" FS "I"
#define MNE_L		"inet:179" FS "L"
#define MNE_N		"inet:180" FS "N"
#define MNE_O		"inet:181" FS "O"
#define MNE_o		"inet:182" FS "o"
#define MNE_P		"inet:183" FS "P"
#define MNE_R		"inet:184" FS "R"
#define MNE_S		"inet:185" FS "S"
#define MNE_T		"inet:186" FS "T"
#define MNE_U		"inet:187" FS "U"
#define MNE_V		"inet:188" FS "V"
#define MNE_x		"inet:189" FS "x"
#define ACC_MetaN	"inet:190" FS "Meta+N"
#define ACC_MetaC	"inet:191" FS "Meta+C"
#define ACC_MetaO	"inet:192" FS "Meta+O"
#define ACC_Metao	"inet:193" FS "Meta+o"
#define ACC_MetaD	"inet:194" FS "Meta+D"
#define ACC_MetaP	"inet:195" FS "Meta+P"

/* ====> rephase the existing messages */

#define TXT_servers2   "inet:196" FS	"DNS Servers"
#define TXT_network_id2	       "inet:197" FS	"Network ID:"
#define TXT_host_id2   "inet:198" FS	"System ID:"
#define TXT_cur_status2	       "inet:199" FS	"Current Status:"
#define TXT_accepted2  "inet:200" FS	"Accepting from %s"
#define TXT_rejected2  "inet:201" FS	"Rejecting from %s"
#define TXT_inUucpFile2	       "inet:202" FS	"UUCP Transfers from %s are already being accepted."
#define TXT_notInUucpFile2     "inet:203" FS	"UUCP Transfers from %s are already being rejected."

#define TXT_reject	"inet:204" FS	 "Reject"
#define INFO_getUserInput	"inet:205" FS	"The Name Server(s) you entered for domain %s is/are not available.\n\nDo You want to continue to use your set of entries?"

/* ====== New q5 messages ====== */

#define ERR_noDnsSetup	"inet:206" FS	"No Dns Setup"
#define INFO_systemNeed2 "inet:207" FS	"You must enter a valid System Name."
#define TXT_nsaView2	"inet:208" FS	"Internet Setup: DNS Access"
#define INFO_addrNeed2 	"inet:209" FS	"You must enter a valid Network Address."
#define	ERR_routeSaveErrors	"inet:210" FS "Several errors have occurred while writing out the system files.\nPlease consult with a system administrator. Your networking may not\nbe usable at this point."
#define	ERR_nisStartUp1	"inet:211" FS "The Network Information System (NIS) package, \"nis\" has not been installed.\nYou must install this package before using NIS Access."
#define ERR_nisInit	"inet:212" FS "Note: A fatal error was detected during NIS Access initialization.\nPlease contact your system administrator."
#define ERR_nisNoServers	"inet:213" FS "You must add at least one NIS Server to the server list."
#define ERR_nisNoDomain	"inet:214" FS "Please specify an NIS Domain Name."
#define ERR_dnsIncomplete	"inet:215" FS "You must fill out the form completely and add at least one server\nto the list of DNS Servers."
#define MiniHelp_sla1	"inet:216" FS "Specify which remote system users will log in from."
#define MiniHelp_sla2	"inet:217" FS "Setup access for remote users with local accounts."
#define MiniHelp_sla3	"inet:218" FS "Setup access to your personal account."
#define MiniHelp_sla4	"inet:219" FS "Indicate who may log in without a password."
#define MiniHelp_sla5	"inet:220" FS "Indicate a specific user who may log in."
#define MiniHelp_dns1	"inet:221" FS "Enter the name of your organization's domain."
#define MiniHelp_dns2	"inet:222" FS "Enter the name of your DNS server."
#define MiniHelp_dns3	"inet:223" FS "Enter the DNS Server's address."
#define MiniHelp_nis1	"inet:224" FS "Enter the name of your organization's domain."
#define MiniHelp_nis2	"inet:225" FS "Enter the name of your NIS server."
#define MiniHelp_nis3	"inet:226" FS "Enter the NIS Server's address."
#define MiniHelp_route1	"inet:227" FS "How should your Network Address be interpreted?"
#define MiniHelp_route2	"inet:228" FS "Enter the name of a router in your network."
#define MiniHelp_route3	"inet:229" FS "Enter the router's address."
#define MiniHelp_route4	"inet:230" FS "Is routing info. broadcasted on your network?"
#define MiniHelp_new1	"inet:231" FS "Enter the name of a system you want to access."
#define MiniHelp_new2	"inet:232" FS "Enter the system's address."
#define MiniHelp_new3	"inet:233" FS "Who owns the system? Where is it located?"
#define ERR_nisIncomplete	"inet:234" FS "You must fill out the form completely and add at least one server\nto the list of NIS Servers."
#define ERR_disablingDNS	"inet:235" FS "You have removed all DNS servers from the system\nand DNS has been disabled."

/* ====== New q6 messages ====== */
#define INFO_sameNameNoQuery2	"inet:236" FS	"Please enter a new System Name."
#define TXT_ruaTitle	"inet:237" FS "Internet Setup: Remote User Access"
#define TXT_ruaSysName	"inet:238" FS "Remote System Name:"
#define TXT_ruaRestrict	"inet:239" FS "Remove Password Restriction For:"
#define TXT_ruaRestrictUser	"inet:240" FS "Remote Users with Local Accounts"
#define TXT_ruaRestrictPers	"inet:241" FS "Access to Your Personal Account"
#define TXT_ruaRhostsMenu	"inet:242" FS "Users on %s Who May Freely Access Your Account"
#define TXT_ruaEquivMenu	"inet:243" FS "Users on %s Who May Freely Access Their Accounts"
#define WARN_ruaRhostsWarning	"inet:244" FS "Warning: The users you specify will be able to access your account\nwithout entering a password. They will be able to access all of your\nfiles and run any program that you can run. Be sure that you only\ngive access to your account to users whom you trust."
#define WARN_ruaEquivWarning	"inet:245" FS "Warning: The users you specify will be able to access any local\nuser account without entering a password (except 'root'). They\nwill be able to access any user's files and run any program that\nuser can run. Be sure that you only give 'Entire System' access to\nusers whom you trust."
#define WARN_ruaEquivNotSaved	"inet:246" FS "Warning: You have not saved the changes for access to\nthe Entire System. Do you want to save the changes?"
#define WARN_ruaRhostsNotSaved	"inet:247" FS "Warning: You have not saved the changes for access to\nYour Account. Do you want to save the changes?"
#define MENU_rua	"inet:248" FS "Remote User Access..."
#define ERR_uucpError1	"inet:249" FS "You must fill out the form completely by providing\nboth a System Name and a Network Address."
#define ERR_noDnsSetup2	"inet:250" FS	"Although DNS is configured, it is not available right now."
#define TXT_Yes	"inet:251" FS "Yes"
#define TXT_No	"inet:252" FS "No"
#define WARN_uucpEntryExists	"inet:253" FS "An entry for %s (address %s)\nexists already. Do you want to remove it?"
#define	ERR_routeSaveErrors2	"inet:254" FS "Several errors have occurred while writing out the system files.\nThe original contents of these files have been restore and the\nsystem in unchanged. Please consult with a system administrator\nabout the errors."
#define WARN_personalAcctSpecificUsers "inet:255" FS "Warning: The users you specify will be able to access your account\nwithout entering a password. They will be able to access all your\nfiles and run any program that you can run. Be sure that you only\ngive access to your account to users whom you absolutely trust."
#define WARN_otherAcctSpecificUsers "inet:256" FS "Warning: the users you specify will be able to access their local\naccount without entering a password. You should only remove password\nrestrictions for these users if they will be running applications\nfrom the specified remote system that require unrestricted access to\ntheir account on your system."
#define WARN_otherAcctAllUsers "inet:257" FS "Warning: any user on the specified remote system that has an\naccount on your system will be able to access his / her account\nwithout entering a password. You should only remove password restrictions\nfor these users if they will be running applications from the remote\nsystem that require unrestricted access to your system."
#define WARN_switchAccessRightsOLD "inet:258" FS "Warning: You did not save the changes you just entered before choosing\na different 'Set Access Rights For' category. If you intended to\nsave those changes, re-enter them then click 'OK'."
#define 	TXT_internetSearch	"inet:259" FS "Internet Setup: Search"

/* ====== New q8 messages ====== */

#define ERR_clsFillOutForm1	"inet:260" FS "At a minimum, you must fill in the System Name Network Address\nfield completely (the Comment field is optional). If you choose\nto configure DNS now, you must fill out the Domain Name,\nName Server, and Network Address fields completely."
#define MNE_actions		"inet:261" FS "A"
#define MNE_actionsRUA		"inet:262" FS "A"
#define MNE_actionsUUCP		"inet:263" FS "U"
#define MNE_actionsDNS		"inet:264" FS "D"
#define MNE_actionsNIS		"inet:265" FS "N"
#define MNE_actionsROUTE	"inet:266" FS "R"
#define MNE_actionsEXIT		"inet:267" FS "x"
#define MNE_system		"inet:268" FS "S"
#define MNE_systemNEW		"inet:269" FS "N"
#define MNE_systemCTF		"inet:270" FS "C"
#define MNE_systemCTSL		"inet:271" FS "S"
#define MNE_systemDEL		"inet:272" FS "D"
#define MNE_systemPROP		"inet:273" FS "P"
#define MNE_view		"inet:274" FS "V"
#define MNE_viewSYS		"inet:275" FS "S"
#define MNE_viewDOM		"inet:276" FS "D"
#define MNE_viewLEFT		"inet:277" FS "L"
#define MNE_viewRIGHT		"inet:278" FS "R"
#define MNE_find		"inet:279" FS "F"
#define MNE_findSEARCH		"inet:280" FS "S"
#define MNE_findFIRST		"inet:281" FS "F"
#define MNE_findLAST		"inet:282" FS "L"
#define MNE_help		"inet:283" FS "H"
#define MNE_helpINT		"inet:284" FS "I"
#define MNE_helpTOC		"inet:285" FS "T"
#define MNE_helpHELP		"inet:286" FS "H"

/* ====== New q9 messages ====== */

#define WARN_switchAccessRights "inet:287" FS "Warning: You did not save the changes you just entered before choosing\na different 'Remove Password Restriction For' category. If you intended\nto save those changes, re-enter them then click 'OK'."
#define MNE_getAddr	"inet:288" FS "G"
#define MNE_OK		"inet:289" FS "O"
#define MNE_Apply	"inet:290" FS "A"
#define MNE_Reset	"inet:291" FS "R"
#define MNE_Cancel	"inet:292" FS "C"
#define MNE_accept	"inet:293" FS "A"
#define MNE_reject	"inet:294" FS "R"
#define MNE_add		"inet:295" FS "A"
#define MNE_modify	"inet:296" FS "M"
#define MNE_delete	"inet:297" FS "D"
#define MNE_Search	"inet:298" FS "S"
#define MNE_Help	"inet:299" FS "H"
#define MNE_Copy	"inet:300" FS "o"
