#!/bin/ksh
#ident	"@(#)siginet	1.2"
#		copyright	"%c%"
#
# (c)Copyright Hewlett-Packard Company 1991.  All Rights Reserved.
# (c)Copyright 1983 Regents of the University of California
# (c)Copyright 1988, 1989 by Carnegie Mellon University
# 
#                          RESTRICTED RIGHTS LEGEND
# Use, duplication, or disclosure by the U.S. Government is subject to
# restrictions as set forth in sub-paragraph (c)(1)(ii) of the Rights in
# Technical Data and Computer Software clause in DFARS 252.227-7013.
#
#                          Hewlett-Packard Company
#                          3000 Hanover Street
#                          Palo Alto, CA 94304 U.S.A.
#

echo "" | $LOGIT

PID=`ps -ef -o "pid comm"  | awk '($2 == "inetd" ) { print $1; exit 0}'`
echo $PID
if [ -z "$PID" ]
then
    echo "WARNING: No inetd process running!!" | $LOGIT
else
      kill -HUP $PID
      echo "Signalled inetd to re-read /etc/inetd.conf" | $LOGIT
fi
