/*		copyright	"%c%" 	*/

#ifndef	NOIDENT
#ident	"@(#)dtadmin:dialup/error.h	1.55.1.2"
#endif

#ifndef __Ol_Dialup_Error_h__
#define __Ol_Dialup_Error_h__
#include <Gizmos.h>

#define FILE_INDEX 0
#define EDIT_INDEX 1
#define VIEW_INDEX 2
#define HELP_INDEX 3
#define DHELP_INDEX 2

#define NEW_INDEX 0
#define FOLDER_INDEX 1
#define DELETE_INDEX 2
#define PROP_INDEX 3



#define	HELP_FILE		"dtadmin/DialMgr.hlp"

#define GGT GetGizmoText
#define SET_HELP(id)		(id.title = GGT(id.title),\
				id.section = id.section?GGT(id.section):0)
#define SET_LABEL(id,n,name)    id[n].label = (XtArgVal)GGT(label##_##name);\
                                id[n].mnemonic = (XtArgVal)*GGT(mnemonic##_##name);

/* WARNING DO NOT USE EMPTY NUMBERS THEY HAVE BEEN USED BEFORE. START
	AT THE END OF EACH TYPE OF SEQUENCE */
#define	format_usage		"DialupMgr:001" FS "Usage: %s [filename]"

#define	string_noAccessPortDir	"DialupMgr:100" FS "Unable to create \".port\" folder for storing modem defaults."
#define	string_appName		"DialupMgr:101" FS "Dialup Setup"
#define	string_badName		"DialupMgr:102" FS "Invalid System Name."
#define	string_badPhone		"DialupMgr:103" FS "Invalid Phone Number."
#define	string_blankName	"DialupMgr:104" FS "You must provide a System Name!"
#define	string_noLogin		"DialupMgr:105" FS "Cannot determine who you are!"
#define	string_noPublic		"DialupMgr:106" FS "'/var/spool/uucppublic' does not exist!"
#define	string_noAccessPublic	"DialupMgr:107" FS "'/var/spool/uucppublic' has wrong permissions!"
#define	string_noCreatePublic	"DialupMgr:108" FS "Cannot create folder under '/var/spool/uucppublic'!"
#define	string_sameNode		"DialupMgr:109" FS "Cannot install an icon for your own system!"
#define	string_noSelect		"DialupMgr:112" FS "You have not selected anything!"
#define	string_fopenWrite	"DialupMgr:113" FS "Failed to open %s for writing."
#define	string_updated		"DialupMgr:114" FS "Systems List saved."
#define	string_deleteConfirm	"DialupMgr:115" FS "Delete %s.  Are you sure?"
#define	string_noAccessNodeDir	"DialupMgr:116" FS "Could not create folder under '/var/spool/uucppublic'."
#define	string_noItem		"DialupMgr:117" FS "There are no items in this window."
#define	string_noMultiple	"DialupMgr:119" FS "Can only install one system at a time."
#define	string_pathDeny		"DialupMgr:120" FS "\"%s\" path does not exist or permission to access is denied."
#define	string_pathExist	"DialupMgr:121" FS "\"%s\" already exist!"
#define	string_longFilename	"DialupMgr:122" FS "\"%s\" is too long!  Must be 14 characters or less."
#define	string_notFound		"DialupMgr:123" FS "System specified not in the list!"
#define	string_blankPhone	"DialupMgr:124" FS "You must provide a phone number!"
#define	string_invalidChar	"DialupMgr:125" FS "Invalid character: '%c'."
#define	string_exceed58		"DialupMgr:126" FS "Phone number can not exceed 58 digits!"
#define	string_connectFail	"DialupMgr:127" FS "Connect failed."
#define	string_lostConnect	"DialupMgr:128" FS "Lost Connect."
#define	string_lostCarrier	"DialupMgr:129" FS "Lost Carrier."
#define	string_dialFail		"DialupMgr:130" FS "Dial failed."
#define	string_scriptFail	"DialupMgr:131" FS "Caller script failed."
#define	string_noDevice		"DialupMgr:132" FS "Device not available."
#define	string_noSystem		"DialupMgr:133" FS "System not in the system list."
#define	string_unknownFail	"DialupMgr:134" FS "Connect failed for unknown reason."
#define	string_startCU		"DialupMgr:135" FS "Calling ..."
#define	string_deviceFail	"DialupMgr:136" FS "Device failed."
#define	string_itemNotSave	"DialupMgr:137" FS "Current entry changes not saved..."
#define	string_startRFT		"DialupMgr:138" FS "Copying ..."
#define	string_badSystem	"DialupMgr:139" FS "Destination system name is invalid."
#define	string_badFile 		"DialupMgr:140" FS "Can not get file(s) status."
#define	string_badFileName	"DialupMgr:141" FS "File(s) to be transferred has invalid filename(s)."
#define	string_folderDeny	"DialupMgr:142" FS "Can not read the folder."
#define	string_folderEmpty	"DialupMgr:143" FS "Folder empty!"
#define	string_partialFail	"DialupMgr:144" FS "Request  partially completed.  An error report will be sent to you via mail."
#define	string_killedCU		"DialupMgr:145" FS "cu terminated by a kill signal."
#define	string_forkFail		"DialupMgr:146" FS "Can not create a new process."
#define	string_usageCU		"DialupMgr:147" FS "Half duplex mode and Odd parity can not be specified at the same time."
#define	string_openFail		"DialupMgr:148" FS "Can't open %s."
#define	string_accessFail	"DialupMgr:149" FS "Can't access %s."
#define	string_writeFail	"DialupMgr:150" FS "Can't write to %s."
#define	string_createFail	"DialupMgr:151" FS "Can't create %s."
#define	string_saved		"DialupMgr:153" FS "Devices Item saved."
#define	string_noFile		"DialupMgr:154" FS "'%s' does not exist and you are not authorized to create it!"
#define	string_unKnown		"DialupMgr:155" FS "%f is unkown.  Check the Address entry for %f in the Internet Setup or Dialup Setup icons."
#define	string_pauseChar	"DialupMgr:156" FS "Invalid character: ','. Enter a dash (-) to specify a pause."
#define string_badExpect	"DialupMgr:157" FS "Invalid string (spaces not allowed)."
#define string_useModem		"DialupMgr:158" FS "entry has unknown type; set it to Modem Type"
#define	label_actions		"DialupMgr:210" FS "Actions"
#define	label_msystem		"DialupMgr:211" FS "System"
#define	label_mdevice		"DialupMgr:212" FS "Device"
#define	label_search		"DialupMgr:213" FS "Search"
#define	label_devices		"DialupMgr:214" FS "Setup Devices..."
#define	label_dial		"DialupMgr:216" FS "Dial"
#define	label_location		"DialupMgr:219" FS "Location:"
#define	label_help		"DialupMgr:220" FS "Help"
#define	label_save		"DialupMgr:221" FS "Save Systems List"
#define	label_open		"DialupMgr:222" FS "Open"
#define	label_exit		"DialupMgr:223" FS "Exit"
#define	label_add		"DialupMgr:225" FS "Add"
#define	label_new		"DialupMgr:226" FS "New..."
#define	label_delete		"DialupMgr:227" FS "Delete"
#define	label_cancel		"DialupMgr:228" FS "Cancel"
#define	label_find		"DialupMgr:230" FS "Find"
#define	label_first		"DialupMgr:231" FS "First"
#define	label_last		"DialupMgr:232" FS "Last"
#define	label_continue		"DialupMgr:233" FS "Continue"
#define	label_autocall		"DialupMgr:234" FS "AutoCall"
#define	label_properties	"DialupMgr:235" FS "Properties..."
#define	label_apply		"DialupMgr:236" FS "Apply"
#define	label_reset		"DialupMgr:237" FS "Reset"
#define	label_com1		"DialupMgr:238" FS "Com1"
#define	label_com2		"DialupMgr:239" FS "Com2"
#define	label_other		"DialupMgr:240" FS "Other"
#define	label_type		"DialupMgr:241" FS "Type:"
#define	label_name		"DialupMgr:242" FS "Name:"
#define	label_port		"DialupMgr:243" FS "Port:"
#define	label_speed		"DialupMgr:245" FS "Speed:"
#define	label_system		"DialupMgr:246" FS "System Name:"
#define	label_destination	"DialupMgr:247" FS "Destination:"
#define	label_class		"DialupMgr:248" FS "Speed:"
#define	label_phone		"DialupMgr:249" FS "Phone Number:"
#define	label_login		"DialupMgr:250" FS "Login ID:"
#define	label_password		"DialupMgr:251" FS "Password:"
#define	label_phoneOrName	"DialupMgr:254" FS "Phone Number:"
#define	label_parity		"DialupMgr:255" FS "Parity:"
#define	label_duplex		"DialupMgr:256" FS "Duplex Mode:"
#define	label_full		"DialupMgr:257" FS "Full"
#define	label_half		"DialupMgr:258" FS "Half"
#define	label_stopBits		"DialupMgr:259" FS "Stop Bits:"
#define	label_charSize		"DialupMgr:260" FS "Character Size:"
#define	label_direct		"DialupMgr:261" FS "Direct"
#define	label_datakit		"DialupMgr:262" FS "Datakit"
#define	label_penril		"DialupMgr:263" FS "Penril"
#define	label_ventel		"DialupMgr:264" FS "Ventel"
#define	label_hayes		"DialupMgr:265" FS "Hayes"
#define	label_hayesSM1200	"DialupMgr:266" FS "HayesSmart 1200"
#define	label_hayesSM2400	"DialupMgr:267" FS "HayesSmart 2400"
#define	label_att4000		"DialupMgr:268" FS "AT&T 4000"
#define	label_att4024		"DialupMgr:269" FS "AT&T 4024"
#define	label_att2224		"DialupMgr:270" FS "AT&T DATAPHONE 2224"
#define	label_att2248		"DialupMgr:271" FS "AT&T DATAPHONE 2248"
#define	label_att2296		"DialupMgr:272" FS "AT&T DATAPHONE 2296"
#define	label_tb		"DialupMgr:273" FS "Trailblazer"
#define	label_multitech		"DialupMgr:274" FS "MultiTech"
#define	label_b300		"DialupMgr:276" FS "300"
#define	label_b1200		"DialupMgr:277" FS "1200"
#define	label_b2400		"DialupMgr:278" FS "2400"
#define	label_b4800		"DialupMgr:279" FS "4800"
#define	label_b9600		"DialupMgr:280" FS "9600"
#define	label_b19200		"DialupMgr:281" FS "19200"
#define	label_b38400		"DialupMgr:282" FS "38400"
#define	label_even		"DialupMgr:283" FS "Even"
#define	label_odd		"DialupMgr:284" FS "Odd"
#define	label_none		"DialupMgr:285" FS "None"
#define	label_one		"DialupMgr:286" FS "1"
#define	label_two		"DialupMgr:287" FS "2"
#define	label_seven		"DialupMgr:288" FS "7"
#define	label_eight		"DialupMgr:289" FS "8"
#define	label_send		"DialupMgr:293" FS "Send"
#define	label_modem		"DialupMgr:294" FS "Modem"
#define	label_uucp		"DialupMgr:295" FS "UUCP"
#define	label_inet		"DialupMgr:296" FS "Internet"
#define	label_quitWarn		"DialupMgr:298" FS "Quit Warning"
#define	label_ok		"DialupMgr:299" FS "OK"


#define	mnemonic_actions	"DialupMgr:410" FS "A"
#define	mnemonic_msystem	"DialupMgr:411" FS "S"
#define	mnemonic_mdevice	"DialupMgr:412" FS "D"
#define	mnemonic_search		"DialupMgr:413" FS "r"
#define	mnemonic_mdial		"DialupMgr:415" FS "l"
#define	mnemonic_dial		"DialupMgr:416" FS "D"
#define	mnemonic_help		"DialupMgr:419" FS "H"
#define	mnemonic_save		"DialupMgr:420" FS "S"
#define	mnemonic_open		"DialupMgr:421" FS "O"
#define	mnemonic_exit		"DialupMgr:422" FS "X"
#define	mnemonic_new		"DialupMgr:425" FS "N"
#define	mnemonic_cancel		"DialupMgr:427" FS "C"
#define	mnemonic_find		"DialupMgr:429" FS "F"
#define	mnemonic_continue	"DialupMgr:430" FS "C"
#define	mnemonic_autocall	"DialupMgr:431" FS "A"
#define	mnemonic_properties	"DialupMgr:433" FS "P"
#define	mnemonic_first		"DialupMgr:434" FS "i"
#define	mnemonic_last		"DialupMgr:435" FS "L"
#define	mnemonic_apply		"DialupMgr:436" FS "A"
#define	mnemonic_reset		"DialupMgr:437" FS "R"
#define	mnemonic_toc		"DialupMgr:439" FS "T"
#define	mnemonic_desk		"DialupMgr:440" FS "H"
#define	mnemonic_b1200		"DialupMgr:443" FS "1"
#define	mnemonic_b2400		"DialupMgr:444" FS "2"
#define	mnemonic_b4800		"DialupMgr:445" FS "4"
#define	mnemonic_b9600		"DialupMgr:446" FS "9"
#define	mnemonic_even		"DialupMgr:449" FS "E"
#define	mnemonic_odd		"DialupMgr:450" FS "O"
#define	mnemonic_none		"DialupMgr:451" FS "N"
#define	mnemonic_seven		"DialupMgr:452" FS "7"
#define	mnemonic_eight		"DialupMgr:453" FS "8"
#define	mnemonic_full		"DialupMgr:454" FS "F"
#define	mnemonic_half		"DialupMgr:455" FS "l"
#define	mnemonic_send		"DialupMgr:456" FS "S"
#define	mnemonic_datakit	"DialupMgr:457" FS "k"
#define	mnemonic_modem	 	"DialupMgr:458" FS "M"
#define	mnemonic_uucp		"DialupMgr:459" FS "U"
#define	mnemonic_inet		"DialupMgr:460" FS "I"
#define	mnemonic_ok			"DialupMgr:461" FS "O"

#define	help_setup		"DialupMgr:500" FS "10"
#define	help_find		"DialupMgr:503" FS "150"
#define	help_remote		"DialupMgr:590" FS "10"

#define	title_install		"DialupMgr:600" FS "Install Remote System Icon"
#define	title_dproperties	"DialupMgr:602" FS "Device Properties"
#define	title_devices		"DialupMgr:603" FS "Devices"
#define	title_setup		"DialupMgr:604" FS "Dialup Setup"
#define	title_find		"DialupMgr:606" FS "Find"
#define	title_hinstall		"DialupMgr:607" FS "Install"
#define	title_property		"DialupMgr:608" FS "Properties"
#define	title_toc		"DialupMgr:609" FS "Table of Contents"
#define	title_remote		"DialupMgr:610" FS "Remote System"
#define	title_deleteDev		"DialupMgr:611" FS "Delete Device"
#define	title_deleteSys		"DialupMgr:612" FS "Delete System"
#define	title_supportDev	"DialupMgr:613" FS "Device Type List"
#define title_quickDial         "DialupMgr:614" FS "Dialup Setup: Dial"

#define title_addSys         "DialupMgr:615" FS "Add New System"
#define title_addDev         "DialupMgr:616" FS "Add New Device"
#define title_copyToFolder         "DialupMgr:617" FS "Copy To Folder"
#define	title_properties	"DialupMgr:618" FS "System Properties"
#define	title_dial		"DialupMgr:619" FS "Dial"
#define err_multiple_install	"DialupMgr:620" FS "Multiple installation not supported");
#define label_copyto		"DialupMgr:621" FS "Copy:"
#define label_to		"DialupMgr:622" FS "To:"
#define label_as		"DialupMgr:623" FS "As:"
#define label_folders		"DialupMgr:624" FS "Folders in "
#define mnemonic_copyto		"DialupMgr:625" FS "o"
#define help_systemname		"DialupMgr:626" FS "Enter the System name to dial."
#define help_phone		"DialupMgr:627" FS "Enter the phone number to dial."
#define help_otherspeed		"DialupMgr:628" FS "Enter the speed to use for the call."
#define help_otherdevice		"DialupMgr:629" FS "Enter the name of the device to use for dialing."
#define help_expect		"DialupMgr:630" FS "Enter the expect sequence."
#define help_send		"DialupMgr:631" FS "Enter the send sequence."
#define PARENT_DIRECTORY	"DialupMgr:632" FS "Parent Folder"

#define	string_noAccessDir	"DialupMgr:633" FS "Could not create folder under directory specified."
#define title_category1		"DialupMgr:634" FS "Basic Settings"
#define title_category2		"DialupMgr:635" FS "Login Sequence"
#define title_category		"DialupMgr:636" FS "CATEGORY: "
#define	string_installFailed	"DialupMgr:637" FS "Copy of \"%s\" failed!"
#define	string_installDone	"DialupMgr:638" FS "Copy of \"%s\" done."
#define mnemonic_copy		"DialupMgr:639" FS "o"
#define	mnemonic_devices	"DialupMgr:640" FS "v"
#define	mnemonic_add		"DialupMgr:641" FS "d"
#define	mnemonic_direct		"DialupMgr:642" FS "i"
#define	mnemonic_setup		"DialupMgr:643" FS "p"
#define	label_loginadd		"DialupMgr:644" FS "Add"
#define	mnemonic_loginadd	"DialupMgr:645" FS "A"
#define	string_badSpeed		"DialupMgr:646" FS "Speed must be numeric!"
#define	string_blankSpeed	"DialupMgr:647" FS "You must provide a speed!"
#define	string_printerPort	"DialupMgr:648" FS "The printer is assigned to this port! The port cannot be set to either bi-directional or incoming when the printer is assigned to the port. Resetting to outgoing."
#define	string_mousePort	"DialupMgr:649" FS "The mouse is assigned to this port! The port cannot be set to either bi-directional or incoming when the mouse is assigned to the port. Resetting to outgoing."
#define	help_dial		"DialupMgr:650" FS "170"
#define	help_install		"DialupMgr:651" FS "120"
#define	label_modemType		"DialupMgr:654" FS "Connect Via:"
#define	label_connectTo		"DialupMgr:655" FS "Connects to:"
#define	label_ConfigurePort		"DialupMgr:656" FS "Configure Port As:"
#define	label_biDirectional		"DialupMgr:657" FS "Bi-Directional"
#define	label_outgoingOnly		"DialupMgr:658" FS "Outgoing Only"
#define	label_incomingOnly		"DialupMgr:659" FS "Incoming Only"
#define label_b14400		"DialupMgr:660"	FS "14400"
#define label_loginSeq		"DialupMgr:661"	FS "Login Sequence:"
#define label_currLoginSeq		"DialupMgr:662"	FS "Current Login Sequence:"
#define label_modify		"DialupMgr:663"	FS "Modify"
#define label_copy		"DialupMgr:664"	FS "Copy"
#define label_nolabel		"DialupMgr:665"	FS "       "
#define	label_mdial		"DialupMgr:666" FS "Dial..."
#define	label_install		"DialupMgr:667" FS "Copy To Folder..."
#define	label_mfind		"DialupMgr:668" FS "Search..."
#define	label_prompt		"DialupMgr:669" FS "Prompt:"
#define	label_response		"DialupMgr:670" FS "Response:"
#define	label_any		"DialupMgr:671" FS "Auto-Select"
#define	label_setup		"DialupMgr:672" FS "Dialup Setup" 
#define	label_toc		"DialupMgr:673" FS "Table of Contents"
#define	label_desk		"DialupMgr:674" FS "Help Desk"
#define	label_extra		"DialupMgr:675" FS "Show Other Options"
#define string_noDevices 	"DialupMgr:676" FS "No Devices Have Been Configured."
#define string_system 	"DialupMgr:677" FS "System "
#define string_speed 	"DialupMgr:678" FS "Speed "
#define string_phone 	"DialupMgr:679" FS "Phone "
#define string_prompt 	"DialupMgr:680" FS "Enter the label the remote system will display as a 'prompt'."

#define string_header		"DialupMgr:681" FS "System          Speed   Phone       "
#define	mnemonic_b14400		"DialupMgr:682" FS "z"
#define	mnemonic_modify		"DialupMgr:683" FS "y"
#define	mnemonic_install	"DialupMgr:684" FS "C"
#define	mnemonic_delete		"DialupMgr:685" FS "e"
#define	mnemonic_mfind		"DialupMgr:686" FS "r"
#define	mnemonic_b300		"DialupMgr:687" FS "3"
#define	mnemonic_b19200		"DialupMgr:688" FS "y"
#define	mnemonic_b38400		"DialupMgr:689" FS "x"
#define	help_property		"DialupMgr:690" FS "80"
#define help_dproperty          "DialupMgr:691" FS "20"
#define	err_open_pipe		"DialupMgr:692" FS "Unable to open pipe for %s"
#define	err_fork		"DialupMgr:693" FS "Unable to fork for %s"
#define	err_exec		"DialupMgr:694" FS "Unable to exec %s"
#define	err_close_stdout		"DialupMgr:695" FS "Could not close stdout in child\n"
#define	err_fdopen_pipe		"DialupMgr:696" FS "Could not fdopen pipe of command %s"
#define err_dup			"DialupMgr:697" FS "Could not dup\n"
#define string_badExec		"DialupMgr:698" FS "Can not create a new process\n"
#define	help_dtcall		"DialupMgr:699" FS "170"
#define	help_device		"DialupMgr:700" FS "50"
#define	string_otherPort	"DialupMgr:701" FS "A full pathname for an existing character special device is required, or the device must be an existing character special device in one of the following directories:  /dev, /dev/term, /dev/xt or /dev/pts"
#define	string_badPrompt	"DialupMgr:702" FS "Prompt must be entered."
#define	label_Enabled		"DialupMgr:703" FS "Enabled"
#define	label_Disabled		"DialupMgr:704" FS "Disabled"
#define	label_PortIs		"DialupMgr:705" FS "Port is: "
#define	string_badSpeed2	"DialupMgr:706" FS "The speed is incorrect. Speed must match a label in /etc/ttydefs."
#define	string_badPortChg	"DialupMgr:707" FS "You cannot use this port number, since you have already assigned this device. Select the correct device before applying changes to the device properties."
#define	string_badPortAdd	"DialupMgr:708" FS "You cannot use this port number, since you have already assigned this device."
#define	string_errorEnable	"DialupMgr:709" FS "Error encountered while trying to set the port to %s."
#define	label_b28800		"DialupMgr:710" FS "28800"
#define	string_resetSpeed	"DialupMgr:711" FS "Selected speed is used for modem to modem communication. Computer to modem port speed will be reset to next higher value."
#define	string_badMousePort	"DialupMgr:712" FS "You cannot use this port for a communications device. The mouse is already assigned to this port."
#define	string_badPrinterPort	"DialupMgr:713" FS "You cannot use this port for a communications device. The printer is already assigned to this port."
#define	label_showStatusWindow	"DialupMgr:714" FS "Verbose Dial Status:"
#define	cu_title		"DialupMgr:715" FS "Dial Status:        Press <Enter> or <Del> to close window."
#define	cu_msg		"DialupMgr:716" FS "Press <Enter> to close window.\n"
#define	cu_error		"DialupMgr:717" FS "\n\nAn error has occurred with your call!\n"
#define	cu_newline		"DialupMgr:718" FS "\n"
#define	cu_badargs		"DialupMgr:719" FS "Argument count for dtcu must be greater than 2 and less than 16.\n"
#endif /* __Ol_Dialup_Error_h__ */
