/*	Copyright (c) 1990, 1991, 1992, 1993 Novell, Inc. All Rights Reserved.	*/
/*	Copyright (c) 1993 Novell, Inc. All Rights Reserved.	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef NOIDENT
#pragma ident	"@(#)dtadmin:nfs/text.h	1.34.1.14"
#endif

/*
*  Module:	dtadmin: nfs  Graphical Administration of Network File Sharing
*  File:	text.h:	 text string message definitions (i18n)
*
*  >>>>>>><<<<<<<<                                                          *
*  >>>>WARNING<<<<  The strings "%s" and "%d" in text below must not be     *
*  >>> WARNING <<<  translated; they are C format conversion specifications *
*  >>>>WARNING<<<<  and must be preserved intact in the translated text.    *
*  >>>>>>><<<<<<<<                                                          *
*/


/* Labels */

#define FormalClientName	"filesharing:1" FS  "File Sharing"
#define TXT_ApplicationTitle	"filesharing:2" FS  "File Sharing Setup"
#define TXT_IconLabel		"filesharing:3" FS  "File Sharing"
#define TXT_Label		"filesharing:4" FS  "Icon Name:"
#define TXT_RemotePath		"filesharing:5" FS  "Share-Item to connect:"
#define TXT_LocalPath		"filesharing:6" FS  "Local Folder to connect it to:"
#define TXT_Writable		"filesharing:7" FS  "Connect Share-Item as:"
#define TXT_RemotePriv		"filesharing:8" FS  "Remote privileges:"
#define TXT_MountType		"filesharing:9" FS  "Connection is:"
#define TXT_Description		"filesharing:11" FS "Description:"
#define TXT_LocalPathShare	"filesharing:12" FS "Folder/File to share:"
#define TXT_nfsLocalFolder	"filesharing:13" FS "File Sharing: Local Folder"
#define TXT_dfsharesHeading	"filesharing:14" FS "   Available Share-Items    "
#define TXT_RemoteHosts		"filesharing:15" FS "Remote Host(s):"
#define TXT_RemoteHost		"filesharing:16" FS "Remote System Name:"
#define TXT_bootAdvertise	"filesharing:17" FS "Advertise when NFS starts?"
#define TXT_bootMount		"filesharing:18" FS "Connect when NFS starts?"
#define TXT_DefaultAccess	"filesharing:19" FS "Advertise as:"
#define TXT_AccessExceptions	"filesharing:20" FS "Exceptions:"
#define TXT_Host		"filesharing:21" FS "System Name:"
#define TXT_StatusTitle		"filesharing:22" FS "Status"
#define TXT_dfmountsDesc	"filesharing:23" FS "Remote systems currently connected to local Folders/Files:"
#define TXT_dfmountsHeading	"filesharing:24" FS "Local Folder/File	                      Remote System"
#define TXT_NfsRunning		"filesharing:25" FS "NFS is running"
#define TXT_NfsNotRunning	"filesharing:26" FS "NFS is not running"
#define TXT_BaseRemoteTitle	"filesharing:27" FS "File Sharing Setup: Remote Share-Items"
#define TXT_BaseLocalTitle	"filesharing:28" FS "File Sharing Setup: Local Share-Items"
#define TXT_AddRemoteTitle	"filesharing:29" FS "Add New Share-Item - Remote"
#define TXT_AddLocalTitle	"filesharing:30" FS "File Sharing: Add New Share-Item - Local"
#define TXT_PropertyRemoteTitle	"filesharing:31" FS "File Sharing: Share-Item Properties -  Remote"
#define TXT_PropertyLocalTitle	"filesharing:32" FS "File Sharing: Share-Item Properties -  Local"
#define TXT_HostTitle		"filesharing:33" FS "File Sharing: Remote Systems"
#define TXT_MountPointPrompt	"filesharing:34" FS "Enter Folder to connect Share-Item to"
#define TXT_MountPointTitle	"filesharing:35" FS "File Sharing: Local Folders"
#define TXT_ShareItemPrompt	"filesharing:36" FS "Enter Folder/File to advertise"
#define TXT_ShareItemTitle	"filesharing:37" FS "File Sharing: Share-Item"
#define TXT_ExtendedOpts	"filesharing:38" FS "Extended Options:"

/* Button Labels */

#define TXT_Actions		"filesharing:100" FS "Actions"
#define TXT_Add			"filesharing:101" FS "Add..."
#define TXT_Advertise		"filesharing:102" FS "Advertise"
#define TXT_Apply		"filesharing:103" FS "Apply"
#define TXT_Cancel		"filesharing:104" FS "Cancel"
#define TXT_Delete		"filesharing:105" FS "Delete"
#define TXT_DeleteAll		"filesharing:106" FS "Delete All"
#define TXT_Edit		"filesharing:107" FS "Edit"
#define TXT_Exit		"filesharing:108" FS "Exit"
#define TXT_GetList		"filesharing:109" FS "Show Available Share-Items"
#define TXT_Hard		"filesharing:110" FS "Hard"
#define TXT_Help		"filesharing:111" FS "Help..."
#define TXT_Index		"filesharing:112" FS "Index..."
#define TXT_InsertReadOnly	"filesharing:113" FS "Insert Read Only"
#define TXT_InsertReadWrite	"filesharing:114" FS "Insert Read and Write"
#define TXT_Local		"filesharing:115" FS "Local"
#define TXT_Mount		"filesharing:116" FS "Connect"
#define TXT_NoAccess		"filesharing:117" FS "No Access"
#define TXT_Properties		"filesharing:118" FS "Properties..."
#define TXT_ReadOnly		"filesharing:119" FS "Read Only"
#define TXT_ReadWrite		"filesharing:120" FS "Read and Write"
#define TXT_Remote		"filesharing:121" FS "Remote"
#define TXT_Reset		"filesharing:122" FS "Reset"
#define TXT_Soft		"filesharing:123" FS "Soft"
#define TXT_StartNFS		"filesharing:124" FS "Start NFS"
#define TXT_Status		"filesharing:125" FS "Status..."
#define TXT_StopNFS		"filesharing:126" FS "Stop NFS"
#define TXT_UnAdvertise		"filesharing:127" FS "Unadvertise"
#define TXT_UnMount		"filesharing:128" FS "Unconnect"
#define TXT_Update		"filesharing:129" FS "Update Status"
#define TXT_View		"filesharing:131" FS "View"
#define TXT_DoIt		"filesharing:132" FS "Do It"
#define TXT_SharedItem		"filesharing:133" FS "Shared Item"
#define TXT_FileSharingW	"filesharing:134" FS "File Sharing..."
#define TXT_TOC			"filesharing:135" FS "Table of Contents..."
#define TXT_HelpDesk		"filesharing:136" FS "Help Desk..."
#define TXT_Resource		"filesharing:137" FS "Share-Item"
#define TXT_MountOptions	"filesharing:138" FS "Other command-line options:"
#define TXT_New			"filesharing:139" FS "New..."
#define TXT_GetHost		"filesharing:140" FS "Search..."
#define TXT_Find		"filesharing:141" FS "Find..."
#define TXT_Add2		"filesharing:142" FS "Add"
#define TXT_Create		"filesharing:143" FS "Create"
#define TXT_FindFolder		"filesharing:144" FS "Find Folder..."
#define TXT_HelpMenu		"filesharing:145" FS "Help"
#define TXT_OK			"filesharing:146" FS "OK"

/* Button Mnemonics */

#define CHR_Actions		"filesharing:180" FS "A"
#define CHR_Add			"filesharing:181" FS "A"
#define CHR_Add2		"filesharing:182" FS "A"
#define CHR_Advertise		"filesharing:183" FS "A"
#define CHR_Apply		"filesharing:184" FS "A"
#define CHR_Cancel		"filesharing:185" FS "C"
#define CHR_Delete		"filesharing:186" FS "D"
#define CHR_Delete2		"filesharing:187" FS "e"
#define CHR_DeleteAll		"filesharing:188" FS "l"
#define CHR_Edit		"filesharing:189" FS "E"
#define CHR_Exit		"filesharing:190" FS "x"
#define CHR_GetList		"filesharing:191" FS "v"
#define CHR_Hard		"filesharing:192" FS "D"
#define CHR_Help		"filesharing:193" FS "H"
#define CHR_Index		"filesharing:194" FS "I"
#define CHR_InsertReadOnly	"filesharing:195" FS "I"
#define CHR_InsertReadWrite	"filesharing:196" FS "t"
#define CHR_Local		"filesharing:197" FS "L"
#define CHR_Mount		"filesharing:198" FS "C"
#define CHR_NoAccess		"filesharing:199" FS "X"
#define CHR_Properties		"filesharing:200" FS "P"
#define CHR_ReadOnly		"filesharing:201" FS "o"
#define CHR_ReadWrite		"filesharing:202" FS "w"
#define CHR_Remote		"filesharing:203" FS "R"
#define CHR_Reset		"filesharing:204" FS "R"
#define CHR_Soft		"filesharing:205" FS "t"
#define CHR_StartNFS		"filesharing:206" FS "S"
#define CHR_Status		"filesharing:207" FS "S"
#define CHR_StopNFS		"filesharing:208" FS "p"
#define CHR_UnAdvertise		"filesharing:209" FS "n"
#define CHR_UnMount		"filesharing:210" FS "U"
#define CHR_Update		"filesharing:211" FS "U"
#define CHR_UsingHelp		"filesharing:212" FS "U"
#define CHR_View		"filesharing:213" FS "V"
#define CHR_SharedItem		"filesharing:214" FS "S"
#define CHR_FileSharingW	"filesharing:215" FS "F"
#define CHR_TOC			"filesharing:216" FS "T"
#define CHR_HelpDesk		"filesharing:217" FS "D"
#define CHR_Resource		"filesharing:218" FS "S"
#define CHR_New			"filesharing:219" FS "N"
#define CHR_GetHost		"filesharing:220" FS "S"
#define CHR_GetFind		"filesharing:221" FS "F"
#define CHR_Create		"filesharing:222" FS "R"
#define CHR_HelpMenu		"filesharing:223" FS "H"
#define CHR_Extend		"filesharing:224" FS "+"
#define CHR_DoIt		"filesharing:225" FS "D"
#define CHR_FindFolder		"filesharing:226" FS "F"
#define CHR_Yes			"filesharing:227" FS "Y"
#define CHR_No       		"filesharing:228" FS "N"
#define CHR_Find       		"filesharing:229" FS "F"
#define CHR_OK       		"filesharing:230" FS "O"

/* Interfaces */

/* the following strings must match those printed by dfshares(1M) */
#define TXT_DfsharesReadOnly	"filesharing:251" FS  "ro"
#define TXT_DfsharesReadWrite	"filesharing:252" FS  "rw"
#define TXT_DfsharesDenied	"filesharing:253" FS  "denied"
#define TXT_DfsharesDirectory	"filesharing:254" FS  "directory"
#define TXT_DfsharesFile	"filesharing:255" FS  "file"
#define TXT_DfsharesExecutable	"filesharing:256" FS  "executable"

#define TXT_HelpTitle			"filesharing:317" FS ""

/* Messages */

#define TXT_AlreadyLocal	"filesharing:401" FS "The local view is already displayed."
#define TXT_AlreadyRemote	"filesharing:402" FS "The remote view is already displayed."
#define TXT_AlreadyMounted	"filesharing:403" FS "Already connected to Share-Item."
#define TXT_AlreadyUnMounted	"filesharing:404" FS "Share-Item is already unconnected."
#define TXT_AlreadyUnShared	"filesharing:405" FS "Share-Item is already unadvertised."
#define TXT_AlreadyShared	"filesharing:406" FS "Share-Item is already advertised."
#define TXT_vfstabOpenError	"filesharing:407" FS "Warning: unable to read list of previously added remote folders."
#define TXT_dtvfstabOpenError	"filesharing:408" FS "Warning: unable to find labels of previously added remote folders."
#define TXT_sharetabOpenError	"filesharing:409" FS "Warning: cannot read list of share-items."
#define TXT_mnttabOpenError	"filesharing:410" FS "Warning: cannot read list of connected share-items."
#define TXT_dfstabOpenError	"filesharing:411" FS "Warning: cannot read list of previously added local share-items."
#define TXT_Bad_vfstabEntry	"filesharing:412" FS "File Sharing: Warning: bad vfstab entry, errno = "
#define TXT_Bad_mnttabEntry	"filesharing:413" FS "File Sharing: Warning: bad mnttab entry, errno = "
#define TXT_dfstabReadError	"filesharing:414" FS "File Sharing: Error reading dfstab entry, errno = "
#define TXT_NoMemory		"filesharing:415" FS "Error: Cannot allocate memory."
#define TXT_NothingToMount	"filesharing:416" FS "Please select something to connect first."
#define TXT_NothingToShare	"filesharing:417" FS "Please select something to advertise first."
#define TXT_NothingToUnMount	"filesharing:418" FS "Please select something to unconnect first."
#define TXT_NothingToUnShare	"filesharing:419" FS "Please select something to unadvertise first."
#define TXT_BadVp		"filesharing:420" FS "Error: Folder description missing."
#define TXT_BadOp		"filesharing:421" FS "Error: Folder data missing."
#define TXT_BadDfs		"filesharing:422" FS "Error: Local data missing."
#define TXT_DeleteSucceeded	"filesharing:423" FS "Delete successful."
#define TXT_MountSucceeded	"filesharing:424" FS "%s connected: Share-Item available for use."
#define TXT_MountFailed		"filesharing:425" FS "Could not connect to remote Share-Item."
#define TXT_UnMountSucceeded	"filesharing:426" FS "Successfully unconnected Share-Item."
#define TXT_UnMountFailed	"filesharing:427" FS "Could not unconnect Share-Item."
#define TXT_ShareSucceeded	"filesharing:428" FS "Advertise succeeded: Remote users may now access Share-Item."
#define TXT_UnShareFailed	"filesharing:429" FS "Could not unadvertise Share-Item: Remote users still have access!"
#define TXT_UnShareSucceeded	"filesharing:430" FS "Unadvertise succeeded: Remote users may no longer access Share-Item."
#define TXT_ShareFailed		"filesharing:431" FS "Could not advertise Share-Item."
#define TXT_MultipleHosts	"filesharing:432" FS "Select an entry from \"Search\" list or enter a system name."
#define TXT_SelectFolderProp	"filesharing:433" FS "Must select a Share-Item before clicking \"Properties\"."
#define TXT_SelectFolderDel	"filesharing:434" FS "Must select a share-item before clicking \"Delete\"."
#define TXT_Select1Folder	"filesharing:435" FS "Only one Share-Item at a time may be selected for this operation."
#define TXT_Yes			"filesharing:436" FS "yes"
#define TXT_No			"filesharing:437" FS "no"
#define TXT_tmpfileOpenError	"filesharing:438" FS "File Sharing: could not open temporary vfstab file."
#define TXT_RemoteDeleteFailed	"filesharing:439" FS "Unable to delete Share-Item."
#define TXT_LocalDeleteFailed	"filesharing:440" FS "Unable to delete Share-Item."
#define TXT_RenameError 	"filesharing:441" FS "File Sharing: unable to move \"%s\" to \"%s\". errno =  %d."
#define TXT_HostRequired	"filesharing:442" FS "You must provide a System Name."
#define TXT_PopenFailed		"filesharing:443" FS "popen(%s) failed."
#define TXT_Push0Failed		"filesharing:444" FS "can't push ptem on 0"
#define TXT_Push1Failed		"filesharing:445" FS "can't push ptem on 1"
#define TXT_NFSstatusFailed	"filesharing:446" FS "Could not check the status of NFS."
#define TXT_NFSclientOK		"filesharing:447" FS "Can connect files and folders:    YES"
#define TXT_NFSclientDown	"filesharing:448" FS "Can connect files and folders:    NO"
#define TXT_NFSserverOK		"filesharing:449" FS "Can advertise files and folders:  YES"
#define TXT_NFSserverDown	"filesharing:450" FS "Can advertise files and folders:  NO"
#define TXT_NFScheckingServer	"filesharing:451" FS "Can advertise files and folders:  (updating status)"
#define TXT_NFScheckingClient	"filesharing:452" FS "Can connect files and folders:    (updating status)"
#define TXT_NFSunknown		"filesharing:453" FS "NFS status:  Unknown"

#define TXT_EnterHost	"filesharing:460" FS "You must provide a System Name."
#define TXT_RestartingNFS	"filesharing:461" FS "Stopping and Re-starting NFS..."
#define TXT_RestartingAnyways	"filesharing:462" FS "Attempting to re-start NFS..."
#define TXT_NFSstartFailed	"filesharing:463" FS "Possible problem encountered starting NFS; please click \"Update Status\" to verify"
#define TXT_NFSstartSucceeded	"filesharing:464" FS " "
#define TXT_NFSstopFailed	"filesharing:465" FS "Problem encountered stopping NFS."
#define TXT_NFSstopSucceeded	"filesharing:466" FS " "
#define TXT_RPCstartFailed	"filesharing:467" FS "Could not stop RPC."
#define TXT_RPCstartSucceeded	"filesharing:468" FS " "
#define TXT_EnterLabel		"filesharing:469" FS "Please fill in the label field."
#define TXT_EnterLocalPath	"filesharing:470" FS "Please fill in the local folder field."
#define TXT_EnterRemotePath	"filesharing:471" FS "Please fill in the remote folder field."
#define TXT_DeleteCanceled	"filesharing:472" FS "Nothing Deleted."
#define TXT_ConfirmLocalDelete	"filesharing:473" FS "OK to permamently delete?"
#define TXT_ConfirmRemoteDelete	"filesharing:474" FS "OK to permamently delete?"
#define TXT_ConfirmStop		"filesharing:475" FS "Caution: Stopping NFS will prevent you from accessing remote files and will prevent remote users from accessing your data.\n  Do you want to stop NFS?"
#define TXT_dfmountsFailed	"filesharing:476" FS "Could not get list of systems accessing local files and folders."
#define TXT_dfsharesFailed	"filesharing:477" FS "Could not get list of remote files and folders."
#define TXT_NfsNotStopped	"filesharing:478" FS "NFS not stopped."

#define TXT_MountRetPrefix	"filesharing:498" FS "Could not connect %s%s"
#define TXT_MountExecFailed	"filesharing:499" FS " "
#define TXT_MountRetUnknown	"filesharing:500" FS " "
#define TXT_MountRetUsage	"filesharing:501" FS "Invalid extended option specified."
#define TXT_MountRetOptions	"filesharing:502" FS "Invalid extended option specified."
#define TXT_MountRetArgs	"filesharing:503" FS " "
#define TXT_MountRetMacInstall	"filesharing:504" FS " "
#define TXT_MountRetFstypeMax	"filesharing:505" FS " "
#define TXT_MountRetFstypeOne	"filesharing:506" FS " "
#define TXT_MountRetVfsOpen	"filesharing:507" FS " "
#define TXT_MountRetVfsGetent	"filesharing:508" FS " "
#define TXT_MountRetMntOpen	"filesharing:509" FS " "
#define TXT_MountRetMntLock	"filesharing:510" FS " "
#define TXT_MountRetMntGetent	"filesharing:511" FS " "
#define TXT_MountRetMpStat	"filesharing:512" FS " "
#define TXT_MountRetMpUnk	"filesharing:513" FS " "
#define TXT_MountRetMpAbspath	"filesharing:514" FS " "
#define TXT_MountRetMpExist	"filesharing:515" FS ": Local Folder Missing."
#define TXT_MountRetMpUnklvl	"filesharing:516" FS " "
#define TXT_MountRetMpRange	"filesharing:517" FS " "
#define TXT_MountRetDevUnk	"filesharing:518" FS " "
#define TXT_MountRetDdbNoent	"filesharing:519" FS " "
#define TXT_MountRetDdbInval	"filesharing:520" FS " "
#define TXT_MountRetDdbAccess	"filesharing:521" FS " "
#define TXT_MountRetLvlInval	"filesharing:522" FS " "
#define TXT_MountRetCeiling	"filesharing:523" FS " "
#define TXT_MountRetLvlRange	"filesharing:524" FS " "
#define TXT_MountRetLtdbAccess	"filesharing:525" FS " "
#define TXT_MountRetLvlPrint	"filesharing:526" FS " "
#define TXT_MountRetMallocErr	"filesharing:527" FS ": Out of Memory."
#define TXT_MountRetWaitErr	"filesharing:528" FS " "
#define TXT_MountRetForkErr	"filesharing:529" FS " "
#define TXT_MountRetExecErr	"filesharing:530" FS " "
#define TXT_MountRetExecAccess	"filesharing:531" FS " "
#define TXT_MountRetUsage2	"filesharing:532" FS " "
#define TXT_MountRetEbusy	"filesharing:533" FS ": Another Share-Item connected to Local Folder."
#define TXT_MountRetEperm	"filesharing:534" FS " "
#define TXT_MountRetEnxio	"filesharing:535" FS " "
#define TXT_MountRetEnotdir	"filesharing:536" FS ": Local Folder is actually a file."
#define TXT_MountRetEnoent	"filesharing:537" FS " "
#define TXT_MountRetEinval	"filesharing:538" FS " "
#define TXT_MountRetEnotblk	"filesharing:539" FS " "
#define TXT_MountRetErofs	"filesharing:540" FS " "
#define TXT_MountRetEnospc	"filesharing:541" FS " "
#define TXT_MountRetEnoload	"filesharing:542" FS " "
#define TXT_MountRetEnodev	"filesharing:543" FS " "
#define TXT_MountRetMisc	"filesharing:544" FS " "
#define TXT_MountRetTmpOpen	"filesharing:545" FS " "
#define TXT_MountRetTmpWrite	"filesharing:546" FS " "
#define TXT_MountRetMntOpen2	"filesharing:547" FS " "
#define TXT_MountRetMntLock2	"filesharing:548" FS " "
#define TXT_MountRetMntToolong	"filesharing:549" FS " "
#define TXT_MountRetMntToofew	"filesharing:550" FS " "
#define TXT_MountRetMntToomany	"filesharing:551" FS " "
#define TXT_MountRetVfsOpen2	"filesharing:552" FS " "
#define TXT_MountRetVfsStat	"filesharing:553" FS " "
#define TXT_MountRetVfsNoent	"filesharing:554" FS " "
#define TXT_MountRetMalloc	"filesharing:555" FS ": Out of memory."
#define TXT_MountRetRetry	"filesharing:570" FS ": NFS not running or remote system not responding."
#define TXT_MountRetGiveUp	"filesharing:571" FS ": NFS not running or remote system not responding."
#define TXT_MountRetHP		"filesharing:572" FS ": Connect operation failed - system:path not provided."
#define TXT_MountRetInvOp	"filesharing:573" FS ": Invalid extended option specified."
#define TXT_MountRetServ	"filesharing:574" FS ": Remote system not found."
#define TXT_MountRetAddr	"filesharing:575" FS ": \"nfsd\" daemon not running on remote system."
#define TXT_MountRetSec		"filesharing:576" FS ": Could not negotiate secure protocal."
#define TXT_MountRetAccess	"filesharing:577" FS ": Access denied."
#define TXT_MountRetNoent	"filesharing:578" FS ": Local Folder Missing."
#define TXT_MountRetNfsDown	"filesharing:579" FS ": start NFS then try again."
#define TXT_SpaceNotAllowed	"filesharing:601" FS "Blanks not allowed in options; use commas to separate options."
#define TXT_BadRemotePath	"filesharing:602" FS "Error:  the \"Share-Item to connect\" entry must begin with a slash (/)."
#define TXT_EtcHostOpenFailed	"filesharing:603" FS "Error:  No remote system entries found: add entries with Internet Setup."
#define TXT_UnknownHost		"filesharing:604" FS "Warning:  Unknown system: %s."
#define TXT_HostNotValidated	"filesharing:605" FS "Warning:  Could not validate system name."
#define TXT_WhiteInLabel	"filesharing:606" FS "Error: Icon Name must be one word."
#define TXT_DirNotCreated	"filesharing:607" FS "Warning: Could not create folder."
#define TXT_ConfirmCreate	"filesharing:608" FS "Notice: %s does not exist\n\n Create this Folder?"
#define TXT_EnterFullPath	"filesharing:609" FS "Enter a complete path in \"Local Folder/File\"."
#define TXT_BadPath		"filesharing:610" FS "Error: Invalid \"Local Folder/File\" entry."
#define TXT_PathAccess		"filesharing:611" FS "Error: you do not have permission to access specified \"Local Folder/File\"."
#define TXT_PathMustBeLocal	"filesharing:612" FS "Error: Folder/File must reside on local system."
#define TXT_DirectoryRequired	"filesharing:613" FS "Error: %s must be a folder."
#define TXT_OptionsNotVerified	"filesharing:614" FS "Warning: Could not validate command-line options."
#define TXT_BadMountOptions	"filesharing:615" FS "Error: invalid command-line options entered."
#define TXT_ReselectFolderProp	"filesharing:616" FS "\"Apply\" not performed; no selected Share-Item found."
#define TXT_AddNotRemote	"filesharing:617" FS "\"Add\" not performed; return to \"Remote\" view then try again."
#define TXT_ApplyNotRemote	"filesharing:618" FS "\"Apply\" not performed; return to \"Remote\" view then try again."
#define TXT_AddNotLocal		"filesharing:619" FS "\"Add\" not performed; return to \"Local\" view then try again."
#define TXT_ApplyNotLocal	"filesharing:620" FS "\"Apply\" not performed; return to \"Local\" view then try again."
#define TXT_DoingDfshares	"filesharing:621" FS "Getting list of Available Share-Items; please wait."
#define TXT_dfsharesNoExports	"filesharing:622" FS "%s has no Share-Items advertised."
#define TXT_dfsharesRPCerror	"filesharing:623" FS "NFS is not running on %s."
#define TXT_FirstTime		"filesharing:624" FS "Remote Folders/Files may be accessed by creating a new Share-Item."
#define TXT_MountPointNotEmpty	"filesharing:625" FS "The folder specified in the `Folder to connect it to' field is not empty!\n\nThe files/folders in `%s' will not be available while the `%s' Remote Share-Item is connected.  This might cause applications on your system, or parts of the system itself to become inoperable.\n\nClick `Add' to add and connect to the Share-Item anyway, or click `Cancel' to return to the Add New Share-Item - Remote window."
#define TXT_errLine  "filesharing:626" FS "File Sharing: Error"
#define CHR_LookupBtn		"filesharing:627" FS "L"
#define TXT_LookupBtn		"filesharing:628" FS "Lookup..."

#define TXT_nameLabel   "filesharing:629" FS  "                 Selected System: "
#define TXT_etcHosts    "filesharing:630" FS  "Systems Defined in /etc/hosts :"
#define TXT_domainName  "filesharing:631" FS  "Systems in Domain:"
#define TXT_listSys	"filesharing:632" FS  "Update Listing"
#define CHR_listSys	"filesharing:633" FS  "L"
#define TXT_error	"filesharing:634" FS  "Error Message"
#define BUT_ok		"filesharing:635" FS  "OK"
#define MNEM_ok		"filesharing:636" FS  "O"
#define TXT_noEntries	"filesharing:637" FS  "No entries in /etc/hosts file\n DNS utility not setup"
#define TXT_noDomain	"filesharing:638" FS "No entries in the Domain"
#define TXT_initMsg1	"filesharing:639" FS "Select a system then click OK"
#define TXT_initMsg2	"filesharing:640" FS "Select a system from either list then click OK"
#define TXT_InputHost    "filesharing:641" FS "Type in a host name and then select Update Listing button"
#define TXT_cantList     "filesharing:643" FS "*** Can't list domain %s: "
#define TXT_noInfo	 "filesharing:644" FS "No information"
#define TXT_nonExist     "filesharing:645" FS "Non-existent domain"
#define TXT_ClientName "filesharing:646" FS  "File Sharing"
#define TXT_SysList	"filesharing:647" FS "Systems List"
#define TXT_Unclassified "filesharing:648" FS  "Unclassified error"
#define TXT_debugMsg	"filesharing:649" FS "LOOKUP: File-%s Line-%d: "
#define TXT_commandFail	"filesharing:650" FS "Command (%s) failed on local system: exit code (%d)"
#define TXT_fileOpenErr	"filesharing:651" FS "Cannot Open %s file"
#define TXT_fileCreateErr	"filesharing:652" FS "Cannot create temporary file name"
#define TXT_fileStatErr	"filesharing:653" FS "Cannot Stat %s file"
#define TXT_DomList	"filesharing:654" FS "Domain Listing"


/* These messages are shared with internet setup and need SE's changes */

#define INFO_noHelp     "filesharing:655" FS  "No help facility in q3"
#define ERR_noSetup     "filesharing:656" FS  "Query Name Server; please wait ..."
#define ERR_unkPanePos  "filesharing:657" FS  "Internal Error: Unknown DNS pane position"
#define ERR_unkQuery    "filesharing:658" FS  "Internal Error: Unknown Query type"
#define ERR_cantReadDns "filesharing:659" FS  "Internal Error: Can't read DNS"
#define ERR_cantFork    "filesharing:660" FS  "Internal Error: Can't fork process"
#define INFO_dnsRunning "filesharing:661" FS  "Running Dns... Pres OK to stop the process"
#define INFO_dnsQuery "filesharing:662" FS  "Looking up Domain info. for %s.\n\n This will take a while ..."
#define ERR_noNameServer	"filesharing:663" FS "Cannot find a Name Server for %s"
#define ERR_noSetup1	"filesharing:664" FS	"Cannot display Lookup window.\n\n You do not have any Systems List entries (beyond your own) nor is your system configured for DNS access."
#define ERR_killBySignal	"filesharing:665" FS	"Lookup process terminated."
#define ERR_unknown	"filesharing:666" FS	"Lookup terminated for unknown reason"
#define TXT_etcLabel2	"filesharing:667" FS "Local Systems List (/etc/hosts)"
#define But_Stop	"filesharing:668" FS "Stop"
#define MNEM_Stop	"filesharing:669" FS "S"
#define TXT_error1	"filesharing:670" FS "Error"
#define TXT_dnsQueryTitle	"filesharing:671" FS "Domain Lookup In Progress"
#define TXT_nextPage	"filesharing:672" FS "Next Page"
#define TXT_prevPage	"filesharing:673" FS "Previous Page"
#define ERR_cantOpenEtcHost	"filesharing:674" FS  "Cannot open /etc/hosts file"
#define ERR_cantOpenConf	"filesharing:675" FS  "Cannot open /etc/resolv.conf file"
#define CHR_DomList		"filesharing:676" FS "D"
#define CHR_SysList		"filesharing:677" FS "S"
/* Help strings "" means use the section heading */

#define TXT_RemoteAddHelpTitle		"filesharing:678" FS "File Sharing-Items"
#define TXT_RemotePropHelpTitle		"filesharing:679" FS "File Sharing"
#define TXT_LocalAddHelpTitle		"filesharing:680" FS "File Sharing"
#define TXT_LocalPropHelpTitle		"filesharing:681" FS "File Sharing"
#define TXT_StatusHelpTitle		"filesharing:682" FS "File Sharing"
#define TXT_HostHelpTitle		"filesharing:683" FS "File Sharing"
#define TXT_FindHelpTitle		"filesharing:684" FS "File Sharing"
#define TXT_FindFolderHelpTitle		"filesharing:685" FS "File Sharing"
#define TXT_DeleteLocalHelpTitle	"filesharing:686" FS "File Sharing"
#define TXT_DeleteRemoteHelpTitle	"filesharing:687" FS "File Sharing"
#define TXT_StopNFSHelpTitle		"filesharing:688" FS "File Sharing"
#define TXT_CreateMountPointHelpTitle	"filesharing:689" FS "File Sharing"
#define TXT_CreateFolderHelpTitle	"filesharing:690" FS "File Sharing"
#define TXT_MainHelpTitle		"filesharing:691" FS "File Sharing"
#define TXT_TOCHelpTitle		"filesharing:692" FS "TOC"
#define TXT_HelpDeskHelpTitle		"filesharing:693" FS "Help Desk"
#define TXT_NoAccessError		"filesharing:694" FS "You must enter at least one system name and select either Insert Read Only or Insert Read and Write, when you select No Access."
#define TXT_invalidHost  "filesharing:695" FS "Invalid or Unavailable Domain. "
#define TXT_chgPropertyFail	"filesharing:696" FS "Could not modify Share-Item since the folder for this Share-Item is in use. Close all files in this folder, and change to another folder before trying to do this change."
