#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)getopt:getopt.mk	1.7.5.1"
#ident "$Header$"

#	Makefile for getopt

include $(CMDRULES)

INSDIR = $(USRBIN)
OWN = bin
GRP = bin

LIBDIR = $(USRLIB)

#top#
# Generated by makefile 1.47

MAKEFILE = getopt.mk


MAINS = getopt

LIBMAINS = getoptcvt

OBJECTS =  getopt.o

SOURCES =  getopt.c

all:		$(MAINS) $(LIBMAINS)

getopt:	getopt.o 
	$(CC) -o $@ $@.o $(LDFLAGS) $(LDLIBS) $(SHLIBS)

getoptcvt:
	cp getoptcvt.sh getoptcvt
	$(CH)chmod 777 getoptcvt

getopt.o:	 $(INC)/stdio.h \
		 $(INC)/locale.h \
		 $(INC)/pfmt.h

GLOBALINCS = $(INC)/stdio.h \
	$(INC)/locale.h \
	$(INC)/pfmt.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS) $(LIBMAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

install: all
	$(INS) -f $(INSDIR) -m 0555 -u $(OWN) -g $(GRP) $(MAINS)
	$(INS) -f $(LIBDIR) -m 0555 -u $(OWN) -g $(GRP) $(LIBMAINS)

size: all
	$(SIZE) $(MAINS)

strip: all
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
