#! /bin/sh
#ident	"@(#)OSRcompat:i386/pkg/OSRcompat/postremove	1.1"

#USECUSTOM means to use a custom patch for installing libc.so.1
#otherwise we just use the statically linked mv
#USECUSTOM=1
USECUSTOM=0

xuname=`uname -X`
overs=`expr "$xuname" : '.*Release = \(3\.2v5\.0\..\)'`
if [ $overs != "3.2v5.0.4" -a $USECUSTOM -eq 1 ]
then
  echo "The UDK libc.so.1 was left in place."
  echo "If you wish to restore the original libc.so.1 and the UDK"
  echo "was the last patch applied, you may execute the following command:"
  echo "/etc/custom -R -p SCO:Unix"
  echo "If you have applied other patches you will need to run custom"
  echo "interactively to remove and reapply the appropriate patches."
fi
exit 0
