#ident	"@(#)kern-pdi:io/hba/adsa/him_code/new_names.h	1.1"

#define Adapter_ID	Cfe_AdapterID
#define Release_Level	Cfe_ReleaseLevel
#define Revision_Level	Cfe_RevisionLevel
#define Port_Address	Cfe_PortAddress
#define HA_Data_Ptr	Cfe_HaDataPtr
#define SCSI_Channel	Cfe_SCSIChannel
#define IRQ_Channel	Cfe_IrqChannel
#define DMA_Channel	Cfe_DmaChannel
#define Bus_Release	Cfe_BusRelease
#define Bus_On	Cfe_BusOn
#define Bus_Off	Cfe_BusOff
#define Strobe_On	Cfe_StrobeOn
#define Strobe_Off	Cfe_StrobeOff
#define Threshold	Cfe_Threshold
#define HA_Config_Flags	Cfe_ConfigFlags
#define SCSI_ID	Cfe_ScsiId
#define Max_Targets	Cfe_MaxTargets
#define SCSI_Option	Cfe_ScsiOption
#define Allow_Dscnt	Cfe_AllowDscnt
