/*		copyright	"%c%" 	*/

#ident	"@(#)_xdrMsgs.h	1.2"
#ident	"$Header$"
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>


struct physicalMsgTag {
	long physicalMsgSize;
};
typedef struct physicalMsgTag physicalMsgTag;
bool_t xdr_physicalMsgTag();
