These M4 files are unsupported.

These m4 macros are provided unmodified from the original
Berkeley distribution and will generate a sendmail.cf file
that is not compatible with our Graphical Sendmail Administration tool.

We did add a file in the ostype directory called sco.uw.svr5.m4
which contains the pathname for our sendmail implementation.

If you are more comfortable with the M4 method of configuring sendmail,
please feel free to use them.

