#	copyright	"%c%"

#ident	"@(#)cut:cut.mk	1.4.6.2"

#	Makefile for cut

include $(CMDRULES)

INSDIR = $(USRBIN)
OWN = bin
GRP = bin

LDLIBS = -lw -lgen

#top#
# Generated by makefile 1.47

MAKEFILE = cut.mk

MAINS = cut

OBJECTS =  cut.o

SOURCES =  cut.c

all:		$(MAINS)

cut:		cut.o 
	$(CC) -o $@ cut.o $(LDFLAGS) $(LDLIBS) $(PERFLIBS)

#	source
cut.o:	$(INC)/stdio.h $(INC)/ctype.h $(INC)/sys/euc.h $(INC)/getwidth.h \
	$(INC)/stdlib.h $(INC)/limits.h

GLOBALINCS = $(INC)/ctype.h $(INC)/stdio.h $(INC)/sys/euc.h $(INC)/getwidth.h

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

install: all
	$(INS) -f $(INSDIR) -m 0555 -u $(OWN) -g $(GRP) cut

size: all
	$(SIZE) $(MAINS)

strip: all
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(INSDIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(INSDIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
