#ident	"@(#)ihvkit:display/lfb256/devices/ati/atinames.h	1.1"

/*	Copyright (c) 1993  Intel Corporation	*/
/*		All Rights Reserved		*/

/* ATI register names */

#define ADVFUNC_CNTL		0x4ae8
#define ALU_BG_FN		0xb6ee
#define ALU_FG_FN		0xbaee
#define APERTURE_CNTL		0x6aee
#define ATT_MODE_CNTL		0x02ea
#define AXSTP			0x8ae8
#define BKGD_COLOR		0xa2e8
#define BKGD_MIX		0xb6e8
#define BOUNDS_BOTTOM		0x7eee
#define BOUNDS_LEFT		0x72ee
#define BOUNDS_RIGHT		0x7aee
#define BOUNDS_TOP		0x76ee
#define BRES_COUNT		0x96ee
#define CHIP_ID			0xfaee
#define CLOCK_SEL		0x4aee
#define CMD			0x9ae8
#define CMP_COLOR		0xb2e8
#define CONFIG_STATUS_1		0x12ee
#define CONFIG_STATUS_2		0x16ee
#define CRT_OFFSET_HI		0x2eee
#define CRT_OFFSET_LO		0x2aee
#define CRT_PITCH		0x26ee
#define CURSOR_COLOR_0		0x1aee
#define CURSOR_COLOR_1		0x1aef
#define CURSOR_OFFSET_HI	0x0eee
#define CURSOR_OFFSET_LO	0x0aee
#define CUR_X			0x86e8
#define CUR_Y			0x82e8
#define DAC_DATA		0x02ed
#define DAC_MASK		0x02ea
#define DAC_R_INDEX		0x02eb
#define DAC_W_INDEX		0x02ec
#define DEST_CMP_FN		0xeeee
#define DEST_COLOR_CMP_MASK	0x72ee
#define DEST_X			0x8ee8
#define DEST_X_END		0xaaee
#define DEST_X_START		0xa6ee
#define DEST_Y			0x8ae8
#define DEST_Y_END		0xaeee
#define DIASTP			0x8ee8
#define DISP_CNTL		0x22e8
#define DISP_STATUS		0x02e8
#define DP_CONFIG		0xceee
#define ERR_TERM		0x92e8
#define EXT_CURSOR_COLOR_0	0x3aee
#define EXT_CURSOR_COLOR_1	0x3eee
#define EXT_FIFO_STATUS		0x9aee
#define EXT_GE_CONFIG		0x7aee
#define EXT_GE_STATUS		0x62ee
#define EXT_SCISSOR_B		0xe6ee
#define EXT_SCISSOR_L		0xdaee
#define EXT_SCISSOR_R		0xe2ee
#define EXT_SCISSOR_T		0xdeee
#define EXT_SHORT_STROKE	0xc6ee
#define FIFO_OPT		0x36ee
#define FIFO_TEST_DATA		0x1aee
#define FIFO_TEST_TAG		0x3aee
#define FRGD_COLOR		0xa6e8
#define FRGD_MIX		0xbae8
#define GE_OFFSET_HI		0x72ee
#define GE_OFFSET_LO		0x6eee
#define GE_PITCH		0x76ee
#define GE_STAT			0x9ae8
#define HORZ_CURSOR_OFFSET	0x1eee
#define HORZ_CURSOR_POSN	0x12ee
#define HORZ_OVERSCAN		0x62ee
#define H_DISP			0x06e8
#define H_SYNC_STRT		0x0ae8
#define H_SYNC_WID		0x0ee8
#define H_TOTAL			0x02e8
#define INPUT_CLK_SEL		0x02ed
#define LINEDRAW		0xfeee
#define LINEDRAW_INDEX		0x9aee
#define LINEDRAW_OPT		0xa2ee
#define LOCAL_CONTROL		0x32ee
#define MAJ_AXIS_PCNT		0x96e8
#define MAX_WAITSTATES		0x6aee
#define MEM_BNDRY		0x42ee
#define MEM_CFG			0x5eee
#define MEM_CNTL		0xbee8
#define MIN_AXIS_PCNT		0xbee8
#define MISC_CNTL		0x7eee
#define MISC_OPTIONS		0x36ee
#define MUX_CNTL		0x02eb
#define OUTPUT_CLK_SEL		0x02ea
#define OVERSCAN_BLUE_24	0x02ef
#define OVERSCAN_COLOR_8	0x02ee
#define OVERSCAN_GREEN_24	0x06ee
#define OVERSCAN_RED_24		0x06ef
#define PATTERN_H		0xbee8
#define PATTERN_L		0xbee8
#define PATT_DATA		0x8eee
#define PATT_DATA_INDEX		0x82ee
#define PATT_INDEX		0xd6ee
#define PATT_LENGTH		0xd2ee
#define PCI_CNTL		0x22ee
#define PIXEL_CNTL		0xbee8
#define PIX_TRANS		0xe2e8
#define RD_MASK			0xaee8
#define ROM_ADDR_1		0x52ee
#define R_EXT_GE_CONFIG		0x8eee
#define R_H_SYNC_STRT		0xb6ee
#define R_H_SYNC_WID		0xbaee
#define R_H_TOTAL_AND_DISP	0xb2ee
#define R_MISC_CNTL		0x92ee
#define R_SRC_X			0xdaee
#define R_SRC_Y			0xdeee
#define R_V_DISP		0xc6ee
#define R_V_SYNC_STRT		0xcaee
#define R_V_SYNC_WID		0xd2ee
#define R_V_TOTAL		0xc2ee
#define SCAN_X			0xcaee
#define SCISSOR_B		0xbee8
#define SCISSOR_L		0xbee8
#define SCISSOR_R		0xbee8
#define SCISSOR_T		0xbee8
#define SCRATCH_PAD_0		0x52ee
#define SCRATCH_PAD_1		0x56ee
#define SHADOW_CTL		0x46ee
#define SHADOW_SET		0x5aee
#define SHORT_STROKE		0x9ee8
#define SRC_X			0x8ee8
#define SRC_X_END		0xbeee
#define SRC_X_START		0xb2ee
#define SRC_Y			0x8ae8
#define SRC_Y_DIR		0xc2ee
#define SUBSYS_CNTL		0x42e8
#define SUBSYS_STATUS		0x42e8
#define VERT_CURSOR_OFFSET	0x1eef
#define VERT_CURSOR_POSN	0x16ee
#define VERT_LINE_CNTR		0xceee
#define VERT_OVERSCAN		0x66ee
#define V_DISP			0x16e8
#define V_SYNC_STRT		0x1ae8
#define V_SYNC_WID		0x1ee8
#define V_TOTAL			0x12e8
#define WRT_MASK		0xaae8
