#!/sbin/sh
#ident	"@(#)ktool:i386at/ktool/scodb/idbuild_hook	1.3"

PATH=$PATH:${KTOOL:+$KTOOL:}/etc/conf/bin
ID=$1
OUTFILE=$2

#
# Check if scodb is configured into the kernel or not.
#


if [ ! -f $ID/sdevice.d/scodb ]
then
	exit 0
fi
if [ `grep "^scodb" $ID/sdevice.d/scodb | cut -f 2` = "Y" ]
then
	if [ ! -d $ID/pack.d/scodb/info ]
	then
		echo "WARNING: not building scodb structures"
		exit 0
	fi
	cd $ID/pack.d/scodb/info

	IDTYPE=`idtype`
	if [ -r kstruct.o.$IDTYPE ]
	then
		rm -f kstruct.o
		ln kstruct.o.$IDTYPE kstruct.o
	fi

	ALL=
	for i in *.o
	do
		name=`basename $i .o`
		if [ $name != "kstruct" ]
		then
			ALL="$ALL $name.idef"
		fi
		$ID/pack.d/scodb/info/make_idef -v -o $name.idef $name.o 2> $name.log
	done
	$ID/pack.d/scodb/info/make_info -v -l $ID/cf.d/$OUTFILE -o kstruct.info kstruct.idef $ALL >info.log 2>&1
	$ID/pack.d/scodb/info/lineno -v $ID/cf.d/$OUTFILE kstruct.info >> info.log 2>&1
	$ID/pack.d/scodb/info/info_to_c kstruct.info > $ID/pack.d/scodb/space.c
	exit 0
else
	rm -f kstruct.info
	touch -f kstruct.info
	$ID/pack.d/scodb/info/info_to_c kstruct.info > $ID/pack.d/scodb/space.c
	exit 0
fi

