#!/bin/sh
TTY=`tty`
OUTPUT=${OUTPUT:-$TTY}
echo "Cleaning $*" >>$OUTPUT 2>&1
echo "$OUTPUT" | grep -i "not a tty"
if [ $? = 0 ] ; then 
	rm -f tty.output
	OUTPUT=tty.output
fi
if [ -f $1.c -a -f $1 ] ;then
	echo Removing $1 >>$OUTPUT 2>&1 
	rm $1 >>$OUTPUT 2>&1
fi
if [ -f $1.c -a -f $1.o ] ;then
	echo Removing $1.o >>$OUTPUT 2>&1 
	rm $1.o >>$OUTPUT 2>&1
fi
