#!/bin/ksh
iclist="ic1 ic2"
ic1="tp1"
ic2="tp2 tp3"
tet_startup="startup"
tet_cleanup="cleanup"

startup() {
	echo stest1: startup
	tet_infoline "stest1: startup"
}

cleanup() {
	echo stest1: cleanup
	tet_infoline "stest1: cleanup"
}

tp1() {
	echo "stest1: ic1 tp1"
	tet_infoline "stest1: ic1 tp1"
	echo "stest1: This tp is $tet_thistest, test name is $TET_PNAME"
	tet_infoline "stest1: This tp is $tet_thistest, test name is $TET_PNAME"

	tet_result PASS
}

tp2(){
	echo "stest1: ic2 tp2"
	tet_infoline "stest1: ic2 tp2"
	tet_result FAIL
}

tp3(){
	echo "stest1: ic2 tp3"
	tet_infoline "stest1: ic2 tp3"
	tet_result UNRESOLVED
}

. ${TET_ROOT}/lib/xpg3sh/tcm.sh
