#!/bin/ksh
#
#       @(#) postinstall 1.0 97/07/11
#
# Copyright (c) 1997 The Santa Cruz Operation, Inc.. All Rights Reserved.
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF THE SANTA CRUZ OPERATION INC.
# The copyright notice above does not evidence any actual or intended
# publication of such source code.
#


##################################################################################
#
# scoadmin_reg
#
#       register the install server with scoadmin
#
##################################################################################

scoadmin_reg ()
{
if [ -f /usr/bin/scoadmin ]
then
  /usr/bin/scoadmin -p "Software_Management" -f -c /usr/lib/scoadmin/instsrv/instsrv.obj
fi

}



##################################################################################
#
#  MAIN
#
##################################################################################

# register with scoadmin
scoadmin_reg

# done
installf -f $PKGINST
exit 0

