#ident	"@(#)OSRcmds:sort/sort.mk	1.1"
#	@(#) sort.mk 25.5 95/02/22 
#
#	      UNIX is a registered trademark of AT&T
#		Portions Copyright 1976-1989 AT&T
#	Portions Copyright 1980-1989 Microsoft Corporation
#    Portions Copyright 1983-1995 The Santa Cruz Operation, Inc
#		      All Rights Reserved
#	Copyright (c) 1984, 1986, 1987, 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.
#
#	scol!donaldp	17 Feb 95
#	- Added support for multiple message catalogues.

include $(CMDRULES)
include ../make.inc

#	Makefile for sort 

INTL=-DINTL

DIR = $(OSRDIR)
SUPOS = $(ROOT)/tmp/sup.os

# LDFLAGS = -s $(XPGUTIL) ../lib/libcmd.a

# CFLAGS = -O $(XPGUTIL) -I$(INC)
CFLAGS = -O -I$(INC)

#top#
# Generated by makefile 1.47

MAKEFILE = sort.mk


MAINS = sort

OBJECTS =  sort.o

SOURCES =  sort.c

LIBOSOBJS = ../lib/libos/errorl.o ../lib/libos/errorv.o \
	../lib/libos/psyserrorl.o ../lib/libos/psyserrorv.o \
	../lib/libos/sysmsgstr.o ../lib/libos/libos_intl.o \
	../lib/libos/catgets_sa.o

ALL:		$(MAINS)

sort:		sort.o
	$(CC) $(CFLAGS)  -o sort  sort.o  $(LIBOSOBJS)  $(LDFLAGS)

sort.o:	sort.c sort_msg.h

sort_msg.h:	NLS/en/sort.gen
	$(MKCATDEFS) sort $? >/dev/null
	cat sort_msg.h | sed 's/"sort.cat@Unix"/"OSRsort.cat@Unix"/g' > sort_msgt.h
	mv sort_msgt.h sort_msg.h

sort.o:		 ../include/osr.h $(INC)/stdio.h $(INC)/ctype.h \
		 $(INC)/signal.h $(INC)/wctype.h $(SYSINC)/signal.h \
		 $(SYSINC)/types.h $(SYSINC)/stat.h \
		 $(INC)/values.h 

GLOBALINCS = $(INC)/ctype.h $(INC)/signal.h $(INC)/stdio.h $(INC)/errno.h \
	$(SYSINC)/signal.h $(SYSINC)/stat.h \
	$(SYSINC)/types.h $(INC)/values.h 


clean:
	rm -f $(OBJECTS) sort_msg.h

clobber:
	rm -f $(OBJECTS) $(MAINS) sort_msg.h
	$(DOCATS) -d NLS $@

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(DOCATS) -d NLS $@
	$(INS) -f $(DIR) sort
	$(STRIP) $(DIR)/sort

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
