#ident	"@(#)ksh93:src/lib/libast/sysconf.c	1.1"

/* : : generated by proto : : */

#if !defined(__PROTO__)
#if defined(__STDC__) || defined(__cplusplus) || defined(_proto) || defined(c_plusplus)
#if defined(__cplusplus)
#define __MANGLE__	"C"
#else
#define __MANGLE__
#endif
#define __STDARG__
#define __PROTO__(x)	x
#define __OTORP__(x)
#define __PARAM__(n,o)	n
#if !defined(__STDC__) && !defined(__cplusplus)
#if !defined(c_plusplus)
#define const
#endif
#define signed
#define void		int
#define volatile
#define __V_		char
#else
#define __V_		void
#endif
#else
#define __PROTO__(x)	()
#define __OTORP__(x)	x
#define __PARAM__(n,o)	o
#define __MANGLE__
#define __V_		char
#define const
#define signed
#define void		int
#define volatile
#endif
#if defined(__cplusplus) || defined(c_plusplus)
#define __VARARG__	...
#else
#define __VARARG__
#endif
#if defined(__STDARG__)
#define __VA_START__(p,a)	va_start(p,a)
#else
#define __VA_START__(p,a)	va_start(p)
#endif
#endif
#include <ast.h>
#include <error.h>

/* : : generated by conf from conf.tab : : */

#include "confmap.h"
#include "conflib.h"

long
sysconf __PARAM__((int op), (op)) __OTORP__(int op;){
	int	n;
#if _lib_sysconf
#undef	sysconf
	if ((n = op) >= 0 || -op <= confmap[0] && (n = confmap[-op]) >= 0)
	{
		long	val;
		int	olderrno;
		int	syserrno;

		olderrno = errno;
		errno = 0;
		val = sysconf(n);
		syserrno = errno;
		errno = olderrno;
		if (val != -1L || syserrno == 0)
			return(val);
	}
#endif
	switch (op)
	{
#ifdef	_SC_AIO_LISTIO_MAX
	case _SC_AIO_LISTIO_MAX:
#ifdef	AIO_LISTIO_MAX
		return(AIO_LISTIO_MAX-0);
#else
#ifdef	_POSIX_AIO_LISTIO_MAX
		return(_POSIX_AIO_LISTIO_MAX-0);
#else
		return(2-0);
#endif
#endif
#endif
#ifdef	_SC_AIO_MAX
	case _SC_AIO_MAX:
#ifdef	AIO_MAX
		return(AIO_MAX-0);
#else
#ifdef	_POSIX_AIO_MAX
		return(_POSIX_AIO_MAX-0);
#else
		return(1-0);
#endif
#endif
#endif
#ifdef	_SC_AIO_PRIO_DELTA_MAX
	case _SC_AIO_PRIO_DELTA_MAX:
#ifdef	AIO_PRIO_DELTA_MAX
		return(AIO_PRIO_DELTA_MAX-0);
#else
#ifdef	_POSIX_AIO_PRIO_DELTA_MAX
		return(_POSIX_AIO_PRIO_DELTA_MAX-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_ARG_MAX
	case _SC_ARG_MAX:
#ifdef	ARG_MAX
		return(ARG_MAX-0);
#else
#ifdef	NCARGS
		return(NCARGS-0);
#else
#ifdef	_POSIX_ARG_MAX
		return(_POSIX_ARG_MAX-0);
#else
		return(4096-0);
#endif
#endif
#endif
#endif
#ifdef	_SC_ASYNCHRONOUS_IO
	case _SC_ASYNCHRONOUS_IO:
#ifdef	ASYNCHRONOUS_IO
		return(ASYNCHRONOUS_IO-0);
#else
#ifdef	_POSIX_ASYNCHRONOUS_IO
		return(_POSIX_ASYNCHRONOUS_IO-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_ATEXIT_MAX
	case _SC_ATEXIT_MAX:
#ifdef	ATEXIT_MAX
		return(ATEXIT_MAX-0);
#else
#ifdef	_XOPEN_ATEXIT_MAX
		return(_XOPEN_ATEXIT_MAX-0);
#else
		return(32-0);
#endif
#endif
#endif
#ifdef	_SC_AVPHYS_PAGES
	case _SC_AVPHYS_PAGES:
#ifdef	AVPHYS_PAGES
		return(AVPHYS_PAGES-0);
#else
		break;
#endif
#endif
#ifdef	_SC_BC_BASE_MAX
	case _SC_BC_BASE_MAX:
#ifdef	BC_BASE_MAX
		return(BC_BASE_MAX-0);
#else
#ifdef	_POSIX2_BC_BASE_MAX
		return(_POSIX2_BC_BASE_MAX-0);
#else
		return(99-0);
#endif
#endif
#endif
#ifdef	_SC_BC_DIM_MAX
	case _SC_BC_DIM_MAX:
#ifdef	BC_DIM_MAX
		return(BC_DIM_MAX-0);
#else
#ifdef	_POSIX2_BC_DIM_MAX
		return(_POSIX2_BC_DIM_MAX-0);
#else
		return(2048-0);
#endif
#endif
#endif
#ifdef	_SC_BC_SCALE_MAX
	case _SC_BC_SCALE_MAX:
#ifdef	BC_SCALE_MAX
		return(BC_SCALE_MAX-0);
#else
#ifdef	_POSIX2_BC_SCALE_MAX
		return(_POSIX2_BC_SCALE_MAX-0);
#else
		return(99-0);
#endif
#endif
#endif
#ifdef	_SC_BC_STRING_MAX
	case _SC_BC_STRING_MAX:
#ifdef	BC_STRING_MAX
		return(BC_STRING_MAX-0);
#else
#ifdef	_POSIX2_BC_STRING_MAX
		return(_POSIX2_BC_STRING_MAX-0);
#else
		return(1000-0);
#endif
#endif
#endif
#ifdef	_SC_2_CHAR_TERM
	case _SC_2_CHAR_TERM:
#ifdef	_POSIX2_CHAR_TERM
		return(_POSIX2_CHAR_TERM-0);
#else
		break;
#endif
#endif
#ifdef	_SC_CHILD_MAX
	case _SC_CHILD_MAX:
#ifdef	CHILD_MAX
		return(CHILD_MAX-0);
#else
#ifdef	_LOCAL_CHILD_MAX
		return(_LOCAL_CHILD_MAX-0);
#else
#ifdef	_POSIX_CHILD_MAX
		return(_POSIX_CHILD_MAX-0);
#else
		return(6-0);
#endif
#endif
#endif
#endif
#ifdef	_SC_CKPT
	case _SC_CKPT:
#ifdef	CKPT
		return(CKPT-0);
#else
#ifdef	_POSIX_CKPT
		return(_POSIX_CKPT-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_CLK_TCK
	case _SC_CLK_TCK:
#ifdef	CLK_TCK
		return(CLK_TCK-0);
#else
#ifdef	HZ
		return(HZ-0);
#else
#ifdef	_AST_CLK_TCK
		return(_AST_CLK_TCK-0);
#else
		return(60-0);
#endif
#endif
#endif
#endif
#ifdef	_SC_CLOCKRES_MIN
	case _SC_CLOCKRES_MIN:
#ifdef	CLOCKRES_MIN
		return(CLOCKRES_MIN-0);
#else
#ifdef	_POSIX_CLOCKRES_MIN
		return(_POSIX_CLOCKRES_MIN-0);
#else
		return(1-0);
#endif
#endif
#endif
#ifdef	_SC_COLL_WEIGHTS_MAX
	case _SC_COLL_WEIGHTS_MAX:
#ifdef	COLL_WEIGHTS_MAX
		return(COLL_WEIGHTS_MAX-0);
#else
#ifdef	_POSIX2_COLL_WEIGHTS_MAX
		return(_POSIX2_COLL_WEIGHTS_MAX-0);
#else
		return(2-0);
#endif
#endif
#endif
#ifdef	_SC_XOPEN_CRYPT
	case _SC_XOPEN_CRYPT:
#ifdef	CRYPT
		return(CRYPT-0);
#else
#ifdef	_XOPEN_CRYPT
		return(_XOPEN_CRYPT-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_2_C_BIND
	case _SC_2_C_BIND:
#ifdef	_POSIX2_C_BIND
		return(_POSIX2_C_BIND-0);
#else
		break;
#endif
#endif
#ifdef	_SC_2_C_DEV
	case _SC_2_C_DEV:
#ifdef	_POSIX2_C_DEV
		return(_POSIX2_C_DEV-0);
#else
		break;
#endif
#endif
#ifdef	_SC_2_C_VERSION
	case _SC_2_C_VERSION:
#ifdef	_POSIX2_C_VERSION
		return(_POSIX2_C_VERSION-0);
#else
		break;
#endif
#endif
#ifdef	_SC_DELAYTIMER_MAX
	case _SC_DELAYTIMER_MAX:
#ifdef	DELAYTIMER_MAX
		return(DELAYTIMER_MAX-0);
#else
#ifdef	_POSIX_DELAYTIMER_MAX
		return(_POSIX_DELAYTIMER_MAX-0);
#else
		return(32-0);
#endif
#endif
#endif
#ifdef	_SC_XOPEN_ENH_I18N
	case _SC_XOPEN_ENH_I18N:
#ifdef	ENH_I18N
		return(ENH_I18N-0);
#else
#ifdef	_XOPEN_ENH_I18N
		return(_XOPEN_ENH_I18N-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_EXPR_NEST_MAX
	case _SC_EXPR_NEST_MAX:
#ifdef	EXPR_NEST_MAX
		return(EXPR_NEST_MAX-0);
#else
#ifdef	_POSIX2_EXPR_NEST_MAX
		return(_POSIX2_EXPR_NEST_MAX-0);
#else
		return(32-0);
#endif
#endif
#endif
#ifdef	_SC_FCHR_MAX
	case _SC_FCHR_MAX:
#ifdef	FCHR_MAX
		return(FCHR_MAX-0);
#else
#ifdef	LONG_MAX
		return(LONG_MAX-0);
#else
#ifdef	_SVID_FCHR_MAX
		return(_SVID_FCHR_MAX-0);
#else
		return(2147483647-0);
#endif
#endif
#endif
#endif
#ifdef	_SC_2_FORT_DEV
	case _SC_2_FORT_DEV:
#ifdef	_POSIX2_FORT_DEV
		return(_POSIX2_FORT_DEV-0);
#else
		break;
#endif
#endif
#ifdef	_SC_2_FORT_RUN
	case _SC_2_FORT_RUN:
#ifdef	_POSIX2_FORT_RUN
		return(_POSIX2_FORT_RUN-0);
#else
		break;
#endif
#endif
#ifdef	_SC_FSYNC
	case _SC_FSYNC:
#ifdef	FSYNC
		return(FSYNC-0);
#else
#ifdef	_lib_fsync
		return(_lib_fsync-0);
#else
#ifdef	_POSIX_FSYNC
		return(_POSIX_FSYNC-0);
#else
		break;
#endif
#endif
#endif
#endif
#ifdef	_SC_IOV_MAX
	case _SC_IOV_MAX:
#ifdef	IOV_MAX
		return(IOV_MAX-0);
#else
#ifdef	_XOPEN_IOV_MAX
		return(_XOPEN_IOV_MAX-0);
#else
		return(16-0);
#endif
#endif
#endif
#ifdef	_SC_JOB_CONTROL
	case _SC_JOB_CONTROL:
#ifdef	JOB_CONTROL
		return(JOB_CONTROL-0);
#else
#ifdef	_POSIX_JOB_CONTROL
		return(_POSIX_JOB_CONTROL-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_LINE_MAX
	case _SC_LINE_MAX:
#ifdef	LINE_MAX
		return(LINE_MAX-0);
#else
#ifdef	_POSIX2_LINE_MAX
		return(_POSIX2_LINE_MAX-0);
#else
		return(2048-0);
#endif
#endif
#endif
#ifdef	_SC_LOCALEDEF
	case _SC_LOCALEDEF:
#ifdef	LOCALEDEF
		return(LOCALEDEF-0);
#else
#ifdef	_POSIX_LOCALEDEF
		return(_POSIX_LOCALEDEF-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_2_LOCALEDEF
	case _SC_2_LOCALEDEF:
#ifdef	_POSIX2_LOCALEDEF
		return(_POSIX2_LOCALEDEF-0);
#else
		break;
#endif
#endif
#ifdef	_SC_LOGNAME_MAX
	case _SC_LOGNAME_MAX:
#ifdef	LOGNAME_MAX
		return(LOGNAME_MAX-0);
#else
#ifdef	_SVID_LOGNAME_MAX
		return(_SVID_LOGNAME_MAX-0);
#else
		return(8-0);
#endif
#endif
#endif
#ifdef	_SC_MAPPED_FILES
	case _SC_MAPPED_FILES:
#ifdef	MAPPED_FILES
		return(MAPPED_FILES-0);
#else
#ifdef	_lib_mmap
		return(_lib_mmap-0);
#else
#ifdef	_POSIX_MAPPED_FILES
		return(_POSIX_MAPPED_FILES-0);
#else
		break;
#endif
#endif
#endif
#endif
#ifdef	_SC_MEMLOCK
	case _SC_MEMLOCK:
#ifdef	MEMLOCK
		return(MEMLOCK-0);
#else
#ifdef	_POSIX_MEMLOCK
		return(_POSIX_MEMLOCK-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_MEMLOCK_RANGE
	case _SC_MEMLOCK_RANGE:
#ifdef	MEMLOCK_RANGE
		return(MEMLOCK_RANGE-0);
#else
#ifdef	_POSIX_MEMLOCK_RANGE
		return(_POSIX_MEMLOCK_RANGE-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_MEMORY_PROTECTION
	case _SC_MEMORY_PROTECTION:
#ifdef	MEMORY_PROTECTION
		return(MEMORY_PROTECTION-0);
#else
#ifdef	_POSIX_MEMORY_PROTECTION
		return(_POSIX_MEMORY_PROTECTION-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_MESSAGE_PASSING
	case _SC_MESSAGE_PASSING:
#ifdef	MESSAGE_PASSING
		return(MESSAGE_PASSING-0);
#else
#ifdef	_POSIX_MESSAGE_PASSING
		return(_POSIX_MESSAGE_PASSING-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_MQ_OPEN_MAX
	case _SC_MQ_OPEN_MAX:
#ifdef	MQ_OPEN_MAX
		return(MQ_OPEN_MAX-0);
#else
#ifdef	_POSIX_MQ_OPEN_MAX
		return(_POSIX_MQ_OPEN_MAX-0);
#else
		return(8-0);
#endif
#endif
#endif
#ifdef	_SC_MQ_PRIO_MAX
	case _SC_MQ_PRIO_MAX:
#ifdef	MQ_PRIO_MAX
		return(MQ_PRIO_MAX-0);
#else
#ifdef	_POSIX_MQ_PRIO_MAX
		return(_POSIX_MQ_PRIO_MAX-0);
#else
		return(32-0);
#endif
#endif
#endif
#ifdef	_SC_NACLS_MAX
	case _SC_NACLS_MAX:
#ifdef	NACLS_MAX
		return(NACLS_MAX-0);
#else
		break;
#endif
#endif
#ifdef	_SC_NGROUPS_MAX
	case _SC_NGROUPS_MAX:
#ifdef	NGROUPS_MAX
		return(NGROUPS_MAX-0);
#else
#ifdef	_LOCAL_NGROUPS_MAX
		return(_LOCAL_NGROUPS_MAX-0);
#else
#ifdef	_POSIX_NGROUPS_MAX
		return(_POSIX_NGROUPS_MAX-0);
#else
		return(0-0);
#endif
#endif
#endif
#endif
#ifdef	_SC_NPROCESSORS_CONF
	case _SC_NPROCESSORS_CONF:
#ifdef	NPROCESSORS_CONF
		return(NPROCESSORS_CONF-0);
#else
		break;
#endif
#endif
#ifdef	_SC_NPROCESSORS_ONLN
	case _SC_NPROCESSORS_ONLN:
#ifdef	NPROCESSORS_ONLN
		return(NPROCESSORS_ONLN-0);
#else
		break;
#endif
#endif
#ifdef	_SC_OPEN_MAX
	case _SC_OPEN_MAX:
#ifdef	OPEN_MAX
		return(OPEN_MAX-0);
#else
#ifdef	_LOCAL_OPEN_MAX
		return(_LOCAL_OPEN_MAX-0);
#else
#ifdef	_POSIX_OPEN_MAX
		return(_POSIX_OPEN_MAX-0);
#else
		return(16-0);
#endif
#endif
#endif
#endif
#ifdef	_SC_AES_OS_VERSION
	case _SC_AES_OS_VERSION:
#ifdef	OS_VERSION
		return(OS_VERSION-0);
#else
#ifdef	_AES_OS_VERSION
		return(_AES_OS_VERSION-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_PAGESIZE
	case _SC_PAGESIZE:
#ifdef	PAGESIZE
		return(PAGESIZE-0);
#else
#ifdef	_LOCAL_PAGESIZE
		return(_LOCAL_PAGESIZE-0);
#else
#ifdef	PAGE_SIZE
		return(PAGE_SIZE-0);
#else
		break;
#endif
#endif
#endif
#endif
#ifdef	_SC_PAGE_SIZE
	case _SC_PAGE_SIZE:
#ifdef	PAGE_SIZE
		return(PAGE_SIZE-0);
#else
#ifdef	PAGESIZE
		return(PAGESIZE-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_PASS_MAX
	case _SC_PASS_MAX:
#ifdef	PASS_MAX
		return(PASS_MAX-0);
#else
#ifdef	_SVID_PASS_MAX
		return(_SVID_PASS_MAX-0);
#else
		return(8-0);
#endif
#endif
#endif
#ifdef	_SC_PHYS_PAGES
	case _SC_PHYS_PAGES:
#ifdef	PHYS_PAGES
		return(PHYS_PAGES-0);
#else
		break;
#endif
#endif
#ifdef	_SC_PID_MAX
	case _SC_PID_MAX:
#ifdef	PID_MAX
		return(PID_MAX-0);
#else
#ifdef	_SVID_PID_MAX
		return(_SVID_PID_MAX-0);
#else
		return(30000-0);
#endif
#endif
#endif
#ifdef	_SC_PRIORITIZED_IO
	case _SC_PRIORITIZED_IO:
#ifdef	PRIORITIZED_IO
		return(PRIORITIZED_IO-0);
#else
#ifdef	_POSIX_PRIORITIZED_IO
		return(_POSIX_PRIORITIZED_IO-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_PRIORITY_SCHEDULING
	case _SC_PRIORITY_SCHEDULING:
#ifdef	PRIORITY_SCHEDULING
		return(PRIORITY_SCHEDULING-0);
#else
#ifdef	_POSIX_PRIORITY_SCHEDULING
		return(_POSIX_PRIORITY_SCHEDULING-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_REALTIME_SIGNALS
	case _SC_REALTIME_SIGNALS:
#ifdef	REALTIME_SIGNALS
		return(REALTIME_SIGNALS-0);
#else
#ifdef	_POSIX_REALTIME_SIGNALS
		return(_POSIX_REALTIME_SIGNALS-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_REGEXP
	case _SC_REGEXP:
#ifdef	REGEXP
		return(REGEXP-0);
#else
#ifdef	_POSIX_REGEXP
		return(_POSIX_REGEXP-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_RESOURCE_LIMITS
	case _SC_RESOURCE_LIMITS:
#ifdef	RESOURCE_LIMITS
		return(RESOURCE_LIMITS-0);
#else
#ifdef	_POSIX_RESOURCE_LIMITS
		return(_POSIX_RESOURCE_LIMITS-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_RE_DUP_MAX
	case _SC_RE_DUP_MAX:
#ifdef	RE_DUP_MAX
		return(RE_DUP_MAX-0);
#else
#ifdef	_POSIX2_RE_DUP_MAX
		return(_POSIX2_RE_DUP_MAX-0);
#else
		return(255-0);
#endif
#endif
#endif
#ifdef	_SC_RTSIG_MAX
	case _SC_RTSIG_MAX:
#ifdef	RTSIG_MAX
		return(RTSIG_MAX-0);
#else
#ifdef	_POSIX_RTSIG_MAX
		return(_POSIX_RTSIG_MAX-0);
#else
		return(8-0);
#endif
#endif
#endif
#ifdef	_SC_SAVED_IDS
	case _SC_SAVED_IDS:
#ifdef	SAVED_IDS
		return(SAVED_IDS-0);
#else
#ifdef	_POSIX_SAVED_IDS
		return(_POSIX_SAVED_IDS-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_SEMAPHORES
	case _SC_SEMAPHORES:
#ifdef	SEMAPHORES
		return(SEMAPHORES-0);
#else
#ifdef	_POSIX_SEMAPHORES
		return(_POSIX_SEMAPHORES-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_SEM_NSEMS_MAX
	case _SC_SEM_NSEMS_MAX:
#ifdef	SEM_NSEMS_MAX
		return(SEM_NSEMS_MAX-0);
#else
#ifdef	_POSIX_SEM_NSEMS_MAX
		return(_POSIX_SEM_NSEMS_MAX-0);
#else
		return(256-0);
#endif
#endif
#endif
#ifdef	_SC_SEM_VALUE_MAX
	case _SC_SEM_VALUE_MAX:
#ifdef	SEM_VALUE_MAX
		return(SEM_VALUE_MAX-0);
#else
#ifdef	_POSIX_SEM_VALUE_MAX
		return(_POSIX_SEM_VALUE_MAX-0);
#else
		return(32767-0);
#endif
#endif
#endif
#ifdef	_SC_SHARED_MEMORY_OBJECTS
	case _SC_SHARED_MEMORY_OBJECTS:
#ifdef	SHARED_MEMORY_OBJECTS
		return(SHARED_MEMORY_OBJECTS-0);
#else
#ifdef	_POSIX_SHARED_MEMORY_OBJECTS
		return(_POSIX_SHARED_MEMORY_OBJECTS-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_XOPEN_SHM
	case _SC_XOPEN_SHM:
#ifdef	SHM
		return(SHM-0);
#else
#ifdef	_XOPEN_SHM
		return(_XOPEN_SHM-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_SIGQUEUE_MAX
	case _SC_SIGQUEUE_MAX:
#ifdef	SIGQUEUE_MAX
		return(SIGQUEUE_MAX-0);
#else
#ifdef	_POSIX_SIGQUEUE_MAX
		return(_POSIX_SIGQUEUE_MAX-0);
#else
		return(32-0);
#endif
#endif
#endif
#ifdef	_SC_SIGRT_MAX
	case _SC_SIGRT_MAX:
#ifdef	SIGRT_MAX
		return(SIGRT_MAX-0);
#else
		break;
#endif
#endif
#ifdef	_SC_SIGRT_MIN
	case _SC_SIGRT_MIN:
#ifdef	SIGRT_MIN
		return(SIGRT_MIN-0);
#else
		break;
#endif
#endif
#ifdef	_SC_STD_BLK
	case _SC_STD_BLK:
#ifdef	STD_BLK
		return(STD_BLK-0);
#else
#ifdef	_SVID_STD_BLK
		return(_SVID_STD_BLK-0);
#else
		return(1024-0);
#endif
#endif
#endif
#ifdef	_SC_STREAM_MAX
	case _SC_STREAM_MAX:
#ifdef	STREAM_MAX
		return(STREAM_MAX-0);
#else
#ifdef	OPEN_MAX
		return(OPEN_MAX-0);
#else
#ifdef	_POSIX_STREAM_MAX
		return(_POSIX_STREAM_MAX-0);
#else
		return(8-0);
#endif
#endif
#endif
#endif
#ifdef	_SC_2_SW_DEV
	case _SC_2_SW_DEV:
#ifdef	_POSIX2_SW_DEV
		return(_POSIX2_SW_DEV-0);
#else
		break;
#endif
#endif
#ifdef	_SC_SYNCHRONIZED_IO
	case _SC_SYNCHRONIZED_IO:
#ifdef	SYNCHRONIZED_IO
		return(SYNCHRONIZED_IO-0);
#else
#ifdef	_POSIX_SYNCHRONIZED_IO
		return(_POSIX_SYNCHRONIZED_IO-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_SYSPID_MAX
	case _SC_SYSPID_MAX:
#ifdef	SYSPID_MAX
		return(SYSPID_MAX-0);
#else
#ifdef	_SVID_SYSPID_MAX
		return(_SVID_SYSPID_MAX-0);
#else
		return(2-0);
#endif
#endif
#endif
#ifdef	_SC_TIMERS
	case _SC_TIMERS:
#ifdef	TIMERS
		return(TIMERS-0);
#else
#ifdef	_POSIX_TIMERS
		return(_POSIX_TIMERS-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_TIMER_MAX
	case _SC_TIMER_MAX:
#ifdef	TIMER_MAX
		return(TIMER_MAX-0);
#else
#ifdef	_POSIX_TIMER_MAX
		return(_POSIX_TIMER_MAX-0);
#else
		return(32-0);
#endif
#endif
#endif
#ifdef	_SC_TMP_MAX
	case _SC_TMP_MAX:
#ifdef	TMP_MAX
		return(TMP_MAX-0);
#else
		return(10000-0);
#endif
#endif
#ifdef	_SC_TZNAME_MAX
	case _SC_TZNAME_MAX:
#ifdef	TZNAME_MAX
		return(TZNAME_MAX-0);
#else
#ifdef	_POSIX_TZNAME_MAX
		return(_POSIX_TZNAME_MAX-0);
#else
		return(6-0);
#endif
#endif
#endif
#ifdef	_SC_UID_MAX
	case _SC_UID_MAX:
#ifdef	UID_MAX
		return(UID_MAX-0);
#else
#ifdef	_SVID_UID_MAX
		return(_SVID_UID_MAX-0);
#else
		return(60002-0);
#endif
#endif
#endif
#ifdef	_SC_XOPEN_UNIX
	case _SC_XOPEN_UNIX:
#ifdef	UNIX
		return(UNIX-0);
#else
#ifdef	_XOPEN_UNIX
		return(_XOPEN_UNIX-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_2_UPE
	case _SC_2_UPE:
#ifdef	_POSIX2_UPE
		return(_POSIX2_UPE-0);
#else
		break;
#endif
#endif
#ifdef	_SC_VERSION
	case _SC_VERSION:
#ifdef	VERSION
		return(VERSION-0);
#else
#ifdef	_POSIX_VERSION
		return(_POSIX_VERSION-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_2_VERSION
	case _SC_2_VERSION:
#ifdef	_POSIX2_VERSION
		return(_POSIX2_VERSION-0);
#else
		break;
#endif
#endif
#ifdef	_SC_XOPEN_VERSION
	case _SC_XOPEN_VERSION:
#ifdef	VERSION
		return(VERSION-0);
#else
#ifdef	_XOPEN_VERSION
		return(_XOPEN_VERSION-0);
#else
		break;
#endif
#endif
#endif
#ifdef	_SC_XOPEN_XCU_VERSION
	case _SC_XOPEN_XCU_VERSION:
#ifdef	XCU_VERSION
		return(XCU_VERSION-0);
#else
#ifdef	_XOPEN_XCU_VERSION
		return(_XOPEN_XCU_VERSION-0);
#else
		break;
#endif
#endif
#endif
	default:
		break;
	}
	errno = EINVAL;
	return(-1);
}
