#ident	"@(#)OSRcmds:grep/grep.mk	1.1"
#	@(#) grep.mk 26.1 95/08/23 
#
#	      UNIX is a registered trademark of AT&T
#		Portions Copyright 1976-1989 AT&T
#	Portions Copyright 1980-1989 Microsoft Corporation
#    Portions Copyright 1983-1995 The Santa Cruz Operation, Inc
#		      All Rights Reserved
#	Copyright (c) 1984, 1986, 1987, 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.
#
#	Modification History
#	scol!markhe	3 Aug 92
#	- Added message catalog support for XPG4/POSIX compliance.
#	- fgrep and egrep are now hard links to grep.
#	scol!donaldp	17 Mar 93
#	- Restored the old grep.c as grepfl.c for use on N1/N2
#	scol!donaldp	05 May 93
#	- Stopped the makefile creating the links - the cutting
#	  tools make the links as required
#	scol!ianw	18 Oct 93
#	- Added grepfl.o to OBJECTS, the clean rule then works correctly.
#	scol!ianw	13 May 94
#	- Added -Kold to FLCFLAGS, _bufend is not defined in the USL stdio.h.
#	scol!ianw	24 Jan 95
#	- Modified to work with the BL10 DS, changed -Kold to -a addon.
#	scol!donaldp	14 Feb 95
#	- Added support for multiple message catalogues.
#	scol!ianw	23 Aug 95
#	- Removed support for grep.fl, it is no longer required.
#

include $(CMDRULES)
include ../make.inc

#	Makefile for grep

INTL=-DINTL

DIR = $(OSRDIR)

LDLIBS	=
# LDFLAGS = $(XPGUTIL) -lcmd
LFLAGS = -lcmd

# CFLAGS = -O -I$(INC) $(XPGUTIL)
CFLAGS = -O -I$(INC)

#top#
# Generated by makefile 1.47

MAKEFILE = grep.mk

MAINS = grep

OBJECTS = grep.o

SOURCES = grep.c

LIBOSOBJS = ../lib/libos/errorl.o ../lib/libos/errorv.o \
	../lib/libos/psyserrorl.o ../lib/libos/psyserrorv.o \
	../lib/libos/sysmsgstr.o ../lib/libos/libos_intl.o \
	../lib/libos/catgets_sa.o

ALL:		$(MAINS)

grep:		grep.o
	$(CC) $(CFLAGS) -o grep grep.o $(LIBOSOBJS) $(LDLIBS) $(LDFLAGS)

grep.o:		 $(INC)/stdio.h $(INC)/ctype.h \
		 grep_msg.h grep.c

grep_msg.h:	NLS/en/grep.gen
	$(MKCATDEFS) grep $? >/dev/null
	cat grep_msg.h | sed 's/"grep.cat@Unix"/"OSRgrep.cat@Unix"/g' > grep_msgt.h
	mv grep_msgt.h grep_msg.h

GLOBALINCS = $(INC)/ctype.h $(INC)/regexp.h $(INC)/stdio.h

clean:
	rm -f $(OBJECTS) grep_msg.h

clobber: clean
	rm -f $(MAINS) grep.cat
	$(DOCATS) -d NLS $@

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(DOCATS) -d NLS $@
	$(INS) -f $(DIR) grep

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
