#ident	"@(#)OSRcmds:cpio/cpio.mk	1.1"
#	@(#) cpio.mk 25.10 95/02/23 
#
#	      UNIX is a registered trademark of AT&T
#		Portions Copyright 1976-1989 AT&T
#	Portions Copyright 1980-1989 Microsoft Corporation
#    Portions Copyright 1983-1995 The Santa Cruz Operation, Inc
#		      All Rights Reserved
#	Copyright (c) 1984, 1986, 1987, 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#	MODIFICATION HISTORY
#
#	L001		scol!ashleyb	02 Feb 1994
#	- cpio now appears on N-floppies. Make a small version without
#	  the NIS libraries or internationalisation.
#	L002		scol!ianw	17 Feb 1994
#	- added -lbsd to LDLIBS, necessary now the BSD compatibility functions
#	  have moved to libbsd from libsocket.
#	L003		scol!ianw	28 Jul 1994
#	- Replaced -lrpc -lsocket -lbsd with $(NETLIB).
#       L004		scol!trevorh	 8 Nov 1994
#       - For XPG4/Posix compliance - Added Message catalogue rules 
#	L005		scol!mwatts	06 Nov 1995
#	- Link against libprot, don't build floppy versions
#	L006		scol!donaldp	18 Feb 95
#	- Added support for multiple message catalogues.
#

include $(CMDRULES)
include ../make.inc

#	Makefile for cpio

INTL=-DINTL

DIR = $(OSRDIR)

XTRALIBS = ../lib/libos/errorl.o ../lib/libos/errorv.o \
	../lib/libos/psyserrorl.o ../lib/libos/psyserrorv.o \
	../lib/libos/sysmsgstr.o ../lib/libos/libos_intl.o \
	../lib/libos/catgets_sa.o

# LDLIBS = $(LIBPROT) $(NETLIB)
LDLIBS = $(NETLIB)

LFLAGS = -lgen $(LDLIBS) -L ../lib/libgen -lgen

CFLAGS = -O -I$(INC)

#top#
# Generated by makefile 1.46

# MAKEFILE = Makefile

MAINS = cpio

NAME = cpio

OBJECTS = cpio.o links.o devlist.o bufio.o utility.o inodes.o

SOURCES =  cpio.c links.c devlist.c bufio.c utility.c inodes.c

ALL:		$(MAINS)

cpio:		$(OBJECTS)
	$(CC) $(CFLAGS)  -o cpio $(OBJECTS) $(XTRALIBS) $(LDFLAGS) $(LFLAGS)

cpio.o:	 cpio.h errmsg.h ${NAME}.c ${NAME}_msg.h

devlist.o:	cpio.h errmsg.h ../include/osr.h

bufio.o:	cpio.h errmsg.h cpio_msg.h ../include/osr.h

utility.o:	cpio.h errmsg.h cpio_msg.h ../include/osr.h

inodes.o:	cpio_msg.h

links.o:	cpio_msg.h ../include/osr.h

${NAME}_msg.h:	NLS/en/${NAME}.gen
	$(MKCATDEFS) ${NAME} $? >/dev/null
	cat cpio_msg.h | sed 's/"cpio.cat@Unix"/"OSRcpio.cat@Unix"/g' > cpio_msgt.h
	mv cpio_msgt.h cpio_msg.h

clean:
	rm -f $(OBJECTS) ${NAME}_msg.h

clobber: clean
	rm -f $(OBJECTS) $(MAINS) ${NAME}_msg.h
	$(DOCATS) -d NLS $@

#newmakefile:
#	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(DOCATS) -d NLS $@
	$(INS) -f $(DIR) cpio

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)
