#!/sbin/sh
#ident	"@(#)validhour	1.2"
#ident "$Header$"


################################################################################
#	Module Name: valhour.sh
#	
#	Inputs:
#		$1 - pollhour string 
#	
#	Description: Verify a valid poll hour was entered.
################################################################################
hourlist=` echo $1 | /usr/bin/tr ',' ' ' `
for i in $hourlist
do [ $i -lt 0 -o $i -gt 23 ] && exit 1
done
hourlist=` echo $hourlist | /usr/bin/tr '-' ' ' `
for i in $hourlist
do [ $i -lt 0 -o $i -gt 23 ] && exit 1
done
exit 0
