#!/sbin/sh -
# @(#)cmd.vxvm:unixware/support/vxdevlist.sh	1.2 2/6/97 17:20:24 - cmd.vxvm:unixware/support/vxdevlist.sh
#ident	"@(#)cmd.vxvm:unixware/support/vxdevlist.sh	1.2"

# Copyright(C)1996 VERITAS Software Corporation.  ALL RIGHTS RESERVED.
# UNPUBLISHED -- RIGHTS RESERVED UNDER THE COPYRIGHT
# LAWS OF THE UNITED STATES.  USE OF A COPYRIGHT NOTICE
# IS PRECAUTIONARY ONLY AND DOES NOT IMPLY PUBLICATION
# OR DISCLOSURE.
# 
# THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND
# TRADE SECRETS OF VERITAS SOFTWARE.  USE, DISCLOSURE,
# OR REPRODUCTION IS PROHIBITED WITHOUT THE PRIOR
# EXPRESS WRITTEN PERMISSION OF VERITAS SOFTWARE.
# 
#               RESTRICTED RIGHTS LEGEND
# USE, DUPLICATION, OR DISCLOSURE BY THE GOVERNMENT IS
# SUBJECT TO RESTRICTIONS AS SET FORTH IN SUBPARAGRAPH
# (C) (1) (ii) OF THE RIGHTS IN TECHNICAL DATA AND
# COMPUTER SOFTWARE CLAUSE AT DFARS 252.227-7013.
#               VERITAS SOFTWARE
# 1600 PLYMOUTH STREET, MOUNTAIN VIEW, CA 94043

: ${VOLROOT_DIR:=$__VXVM_ROOT_DIR}
. ${VOL_SCRIPTS_LIB:-$VOLROOT_DIR/usr/lib/vxvm/lib}/vxcommon

set_OS_variables

vxdisk -q list | awk '
BEGIN {
	printf("%-12s %-12s %-12s %s\n", \
	       "DEVICE", "DISK", "GROUP", "STATUS");
}
$1 ~ /c[0-9a-f]*b[0-9a-f]*t[0-9a-f]*d[0-9a-f]*$VOL_FULL_SLICE$/ {
	printf("%-12s %-12s %-12s %s", \
	       substr($1, 1,length($1)-2), $3, $4, $5);
	for (i = 6; i <= NF; i++) {
		printf(" %s", $i);
	}
	printf("\n");
	next
}
$1 != "-" {
	printf("%-12s %-12s %-12s %s", substr($1, 1,length($1)-2), $3, $4, $5);
	for (i = 6; i <= NF; i++) {
		printf(" %s", $i);
	}
	printf("\n");
}'
