$	"@(#)psrsetupOsa.msg	1.2"

$moduleset SCO_PSRSETUPOSA tcl=psrsetupOsa

$ Error messages
$ %s is the number of the processor
SCO_PSRSETUPOSA_ERR_NOPROC   "Could not get info on processor %s"
SCO_PSRSETUPOSA_ERR_NOSTATE  "Could not get state of processor %s"
SCO_PSRSETUPOSA_ERR_NOOFFLN  "Could not take processor %s offline"
SCO_PSRSETUPOSA_ERR_NOONLN   "Could not bring processor %s online"
SCO_PSRSETUPOSA_ERR_NOFORK   "Could not fork process"

$ %s is the name of a command
SCO_PSRSETUPOSA_ERR_NOEXEC   "Could not exec %s"
SCO_PSRSETUPOSA_ERR_NOINFO   "Could not get processor info" 
