#!/bin/perl
@iclist=(ic1);
@ic1=("tp1","tp2","tp3","tp4");

require "common.pl";

sub tp1{
	$tp=tp1;
	&run("-e contrib/api serial-2");
	
	@infolines=grep(/^$TEST_CASE_INFORMATION/,@journal);
	$ac=0;
	&breakup_infoline($infolines[$ac]);
	$message =~ s/test(\d).+$/$1/;
	if ($activity!=$ac || $message!=($ac+2)) {
		&fail;
	} else {
		&pass;
	}
}

sub tp2{
	$tp=tp2;
	$ac=1;
	&breakup_infoline($infolines[$ac]);
	$message =~ s/test(\d).+$/$1/;
	if ($activity!=$ac || $message!=($ac+2)) {
		&fail;
	} else {
		&pass;
	}
}


sub tp3{
	$tp=tp3;
	$ac=2;
	&breakup_infoline($infolines[$ac]);
	$message =~ s/test(\d).+$/$1/;
	if ($activity!=$ac || $message!=($ac+2)) {
		&fail;
	} else {
		&pass;
	}
}


sub tp4{
	$tp=tp4;
	$ac=3;
	&breakup_infoline($infolines[$ac]);
	$message =~ s/test(\d).+$/$1/;
	if ($activity!=$ac || $message!=($ac+2)) {
		&fail;
	} else {
		&pass;
	}
}


require "$ENV{\"TET_ROOT\"}/lib/perl/tcm.pl";
