#!/bin/sh

rm -f x.$$.ps modules.gif.bak
[ -f modules.gif ] && mv modules.gif modules.gif.bak

cp modules.idraw x.$$.ps
echo " "
echo "This will take a few minutes, and eat all your ram..."
#/usr/bin/X11/convert -density 288 -geometry 25% x.$$.ps modules.gif
/usr/bin/X11/convert -density 383 -geometry 25% x.$$.ps modules.gif
rm -f x.$$.ps
echo "File modules.gif is ready to ftp to beefhart"
echo "Also copy modules.idraw to modules.idraw.ps"
echo " "
echo "      ftp beefhart"
echo "	    (login)
echo "      binary"
echo "      cd /home/www/softmgmt/Gemini/design/iqm/"
echo "      put modules.gif"
echo "      put modules.idraw modules.idraw.ps"
echo "      quit"
echo " "



# -density 144 -geometry 50%   if the above takes too much time/mem
