#pragma comment(exestr, "@(#) rce.h 25.6 94/04/27 ")
/*
 *	Copyright (C) The Santa Cruz Operation, 1987-1994.
 */

#ifndef _RCE_H
#define _RCE_H

/*
 * Return codes generated by atdialer
 */

#define	RCE_NULL	RCE_FAIL  	/* General Failure */
#define	RCE_INUSE	(1 | RCE_FAIL) 	/* line in use */
#define	RCE_SIG		(2 | RCE_FAIL)	/* signal aborted dialer */
#define	RCE_ARGS       	(3 | RCE_FAIL)	/* invalid arguments */
#define	RCE_PHNO       	(4 | RCE_FAIL)	/* invalid phone number */
#define	RCE_SPEED	(5 | RCE_FAIL)	/* invalid baud rate -or- bad connect baud */
#define	RCE_OPEN	(6 | RCE_FAIL)	/* can't open line */
#define	RCE_IOCTL	(7 | RCE_FAIL)	/* ioctl error */
#define	RCE_TIMOUT	(8 | RCE_FAIL)	/* timeout */
#define	RCE_NOTONE	(9 | RCE_FAIL)	/* no dial tone */
#define	RCE_BUSY	(13| RCE_FAIL)	/* phone is busy */
#define	RCE_NOCARR	(14| RCE_FAIL)	/* no carrier */
#define	RCE_ANSWER	(15| RCE_FAIL)	/* no answer */
#define	RCE_FAXMODE	0x40		/* Fax received */
#define	RCE_DATAMODE	0x20		/* Data received */

#define	RCE_FAIL	0x80		/* Return code type is fail */


/* Defines for high speed, not defined in termios.h */
#define B57600	16	/* 57600 baud */
#define B76800	17	/* 76800 baud */
#define B115200	18	/* 115200 baud */
#define B230400	19	/* 230400 baud */
#define B460800	20	/* 460800 baud */
#define B921600	21	/* 921600 baud */

#endif /* _RCE_H */
