#	copyright	"%c%"

#ident	"@(#)ksh:ksh.mk	1.8.12.3"
#ident  "$Header$"

include $(CMDRULES)

# makefile for ksh generated by mkold and hand modified

OWN = bin
GRP = root

# for RDS: set INSDIR = $(USRLBIN)/usr/lbin, else $(USRBIN)
INSDIR = $(USRBIN)

all: ksh

ksh: 
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk all
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk all

install: all
	-rm -f $(INSDIR)/ksh
	 $(INS) -o -m 0555 -u $(OWN) -g $(GRP) -f $(INSDIR) sh/ksh
	$(CH)-rm -f $(INSDIR)/rksh
	$(CH)-ln -f $(INSDIR)/ksh $(INSDIR)/rksh

clean:
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk $@
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk $@

clobber: clean
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk $@
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk $@

lintit:
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk $@
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk $@
