$moduleset SCO_RELAX C=relax
$
$
SCO_RELAX_ERR_SU	"you are not authorized to run this program"
SCO_RELAX_ERR_BAD_DIR	"invalid directory_name %s"
SCO_RELAX_ERR_NO_ALLOC	"unable to allocate memory"
SCO_RELAX_ERR_NO_DIR	"directory %s does not exist"
SCO_RELAX_ERR_NOT_DIR	"%s is not a directory"

$ %s is the command name (ie relax)
SCO_RELAX_ERR_USAGE	"usage: %s directory_name\n"
SCO_RELAX_ERR_NO_OPEN	"cannot open file %s"
SCO_RELAX_ERR_SYSDEF	"error reading System Default database updates"
SCO_RELAX_ERR_SYSDEF2	"error reading System Default database"
SCO_RELAX_ERR_SYSDEF3	"error updating System Default database"
SCO_RELAX_ERR_TRUNC	"%1$s: line %2$d truncated as too long"
SCO_RELAX_ERR_READ	"error reading file %s"
SCO_RELAX_ERR_NOT_REG_FILE	"%s is not a regular file"

$ %s is the location of the Bourne Shell program, ie'/bin/sh'
SCO_RELAX_ERR_NO_EXEC	"unable to execute script as %s missing"
SCO_RELAX_ERR_NO_FORK	"Unable to fork to execute authck"
SCO_RELAX_ERR_NO_EXEC2	"Unable to execute script"
SCO_RELAX_ERR_WAIT	"Error waiting for script to complete"

$ %s is a filename
SCO_RELAX_ERR_BAD_FILENAME	"invalid filename %s ignored"
SCO_RELAX_ERR_NO_OPEN2	"unable to open file %s"

$ %s is a pathname for the following 8 messages
SCO_RELAX_ERR_UPDATE_FAIL	"update of %s failed"
SCO_RELAX_ERR_FILEC_DB	"warning %s not listed in File Control Database"
SCO_RELAX_ERR_NO_EXIST	"warning %s does not exist"
SCO_RELAX_ERR_USER_ID	"warning %1$s user ID is %2$d, should be %3$d"
SCO_RELAX_ERR_GRP_ID	"warning %1$s group ID is %2$d, should be %3$d"
SCO_RELAX_ERR_BAD_TYPE	"warning %s invalid type"
SCO_RELAX_ERR_BAD_TYPE2	"warning %1$s type is %2$c, should be %3$c"
SCO_RELAX_ERR_MODE	"warning %1$s mode is %2$04o, should be %3$04o"
SCO_RELAX_ERR_ERROR	"%1$s (error %2$d)"
SCO_RELAX_ERR_SYS_ERR	"Unknown system error %d"
SCO_RELAX_ERR_NO_UPDATE	"unable to open file %s for update"
