#!/bin/sh
# called from .bcfg file
# we should call removef on these files
exec 1>/dev/null
exec 2>/dev/null
/bin/rm -f /etc/init.d/cet
/bin/rm -f /etc/rc2.d/S02cet
/bin/rm -f /etc/rc3.d/S02cet
/bin/rm -f /etc/rc0.d/K98cet
exit 0
