#!/bin/sh
# called from .bcfg file
# we should call installf on these files
exec 1>/dev/null
exec 2>/dev/null
/bin/cp /etc/inst/nd/mdi/cet/S02cet /etc/init.d
/bin/chmod 755 /etc/init.d/cet
/bin/ln /etc/init.d/cet /etc/rc2.d/S02cet
/bin/ln /etc/init.d/cet /etc/rc3.d/S02cet
/bin/ln /etc/init.d/cet /etc/rc0.d/K98cet
exit 0
