.TH pine 1 "Version 3.96"
.SH NAME
pine \- a Program for Internet News and Email
.SH SYNTAX 

.B pine
[
.I options
] [
.I address
,
.I address
] 

.B pinef
[
.I options
] [
.I address
,
.I address
]
.SH DESCRIPTION

Pine is a screen-oriented message-handling tool.  In its default 
configuration, Pine offers an intentionally limited set of 
functions geared toward the novice user, but it also has a growing 
list of optional "power-user" and personal-preference features.
.I pinef 
is a variant of Pine that uses function keys rather than mnemonic 
single-letter commands.
Pine's basic feature set includes:
.IP
View, Save, Export, Delete, Print, Reply and Forward messages.
.IP
Compose messages in a simple editor (Pico) with word-wrap and a spelling
checker.  Messages may be postponed for later completion.
.IP
Full-screen selection and management of message folders.
.IP
Address book to keep a list of long or frequently-used addresses.
Personal distribution lists may be defined.
Addresses may be taken into the address book from
incoming mail without retyping them. 
.IP
New mail checking and notification occurs automatically every 2.5 minutes
and after certain commands, e.g. refresh-screen (Ctrl-L).
.IP
On-line, context-sensitive help screens.
.PP
Pine supports MIME (Multipurpose Internet Mail Extensions), an Internet
Standard for representing multipart and multimedia data in email.
Pine allows you to save MIME objects to files, and in some 
cases, can also initiate the correct program for viewing the object.
It uses the system's
.I mailcap 
configuration file to determine what program can process a particular MIME
object type. 
Pine's message composer does not have integral multimedia capability, but
any type of data file --including multimedia-- can be attached to a text
message and sent using MIME's encoding rules.  This allows any group of
individuals with MIME-capable mail software (e.g. Pine, PC-Pine, or many
other programs) to exchange formatted documents, spread-sheets, image
files, etc, via Internet email. 
.PP
Pine uses the 
.I c-client
messaging API to access local and remote mail folders. This
library provides a variety of low-level message-handling functions, 
including drivers
for a variety of different mail file formats, as well as routines
to access remote mail and news servers, using IMAP (Internet Message
Access Protocol) and NNTP (Network News Transport Protocol).  Outgoing mail
is usually handed-off to the Unix
.IR sendmail ,
program but it can optionally be posted directly via SMTP 
(Simple Mail Transfer Protocol).
.SH OPTIONS
.if n .ta 2.8i
.if t .ta 2.1i

The command line options/arguments are:
.IP \fIaddress\fR 20
Send mail to 
.I address.
This will cause Pine to go directly into the message composer.
.IP \fB-a\fR 20
Special anonymous mode for UWIN*
.IP \fB-c\ \fIcontext-number\fR 20
.I context-number is the number corresponding to the 
folder-collection to which the
.I -f
command line argument should be applied.  By default the
.I -f
argument is applied to the first defined folder-collection.
.IP \fB-d\ \fIdebug-level\fR 20
Output diagnostic info at
.I debug-level
(0-9) to the current
.I .pine-debug[1-4]
file.  A value of 0 turns debugging off and suppresses the
.I .pine-debug
file.
.IP \fB-f\ \fIfolder\fR 20
Open 
.I folder 
(in first defined folder collection) instead of INBOX.
.IP \fB-F\ \fIfile\fR 20
Open named text file and view with Pine's browser.
.IP \fB-h\fR 20
Help: list valid command-line options.
.IP \fB-i\fR 20
Start up in the FOLDER INDEX screen.
.IP \fB-I\ \fIkeystrokes\fR 20
Initial (comma separated list of) keystrokes which Pine should execute
on startup.
.IP \fB-k\fR 20
Use function keys for commands. This is the same as running the command
.IR pinef .
.IP \fB-l\fR 20
Expand all collections in FOLDER LIST display. 
.IP \fB-n\ \fInumber\fR 20
Start up with current message-number set to 
.I number.
.IP \fB-nr\fR 20
Special mode for UWIN*
.IP \fB-o\fR 20
Open first folder read-only.
.IP \fB-p\ \fIconfig-file\fR 20
Use 
.I config-file
as the personal configuration file instead of the default 
.IR .pinerc .
.IP \fB-P\ \fIconfig-file\fR 20
Use 
.I config-file
as the configuration file instead of default
system-wide configuration file 
.IR pine.conf .
.IP \fB-r\fR 20
Use restricted/demo mode.
.I Pine
will only send mail to itself
and functions like save and export are restricted.
.IP \fB-z\fR 20
Enable ^Z and SIGTSTP so pine may be suspended.
.IP \fB-conf\fR 20
Produce a sample/fresh copy of the 
system-wide configuration file,
.I pine.conf,
on the standard output. This is distinct from the per-user
.I .pinerc
file.
.IP \fB-create_lu\ \fIaddrbook\ \fIsort-order\fR 20
Creates auxiliarly index (look-up) file for 
.I addrbook
and sorts 
.I addrbook
in
.I sort-order,
which may be
.I dont-sort, nickname, fullname, nickname-with-lists-last, or fullname-with-lists-last.
Useful when creating global or shared address books.
.IP \fB-pinerc\ \fIfile\fR 20
Output fresh pinerc configuration to 
.I file.
.IP \fB-sort\ \fIorder\fR
Sort the FOLDER INDEX display in one of the following orders: 
.I arrival, subject, from, date, size, orderedsubj
or
.I reverse. Arrival 
order is the default. 
The OrderedSubj choice simulates a threaded sort.
Any sort may be reversed by adding 
.I /reverse
to it.
.I Reverse
by itself is the same as
.IR arrival/reverse .
.IP \fI-option\=\fIvalue\fR 20
Assign 
.I value
to the config option 
.I option
e.g. -signature-file=sig1 or -feature-list=signature-at-bottom 
(Note: feature-list values are additive) 
.PP
* UWIN = University of Washington Information Navigator
.SH CONFIGURATION

There are several levels of Pine configuration.  Configuration values at 
a given level over-ride corresponding values at lower levels.  In order of 
increasing precedence:

 o built-in defaults.
.br
 o system-wide 
.I pine.conf 
file.
.br
 o personal 
.I .pinerc 
file (may be set via built-in Setup/Config menu.)
.br
 o command-line options.
.br
 o system-wide 
.I pine.conf.fixed 
file.

There is one exception to the rule that configuration values are replaced
by the value of the same option in a higher-precedence file: the
feature-list variable has values that are additive, but can be negated by
prepending "no-" in front of an individual feature name. Unix Pine also
uses the following environment variables: 

  TERM
.br
  DISPLAY     (determines if Pine can display IMAGE attachments.)
.br
  SHELL       (if not set, default is /bin/sh )
.br
  MAILCAPS    (semicolon delimited list of path names to mailcap files)
.SH FILES
.if n .ta 2.8i
.if t .ta 2.1i

/usr/spool/mail/xxxx	Default folder for incoming mail.
.br
~/mail	Default directory for mail folders.
.br
~/.addressbook	Default address book file.
.br
~/.addressbook.lu	Default address book index file.
.br
~/.pine-debug[1-4]	Diagnostic log for debugging.
.br
~/.pinerc	Personal pine config file.
.br
~/.newsrc	News subscription/state file.
.br
~/.signature	Default signature file.
.br
~/.mailcap	Personal mail capabilities file.
.br
~/.mime.types	Personal file extension to MIME type mapping
.br
/etc/mailcap	System-wide mail capabilities file.
.br
/etc/mime.types	System-wide file ext. to MIME type mapping
.br
/usr/local/lib/pine.info	Local pointer to system administrator.
.br
/usr/local/lib/pine.conf	System-wide configuration file.
.br
/usr/local/lib/pine.conf.fixed	 Non-overridable configuration file.
.br
/tmp/.\\usr\\spool\\mail\\xxxx	Per-folder mailbox lock files.
.br
~/.pine-interrupted-mail	Message which was interrupted.
.br
~/mail/postponed-msgs	For postponed messages.
.br
~/mail/sent-mail	Outgoing message archive (FCC).
.br
~/mail/saved-messages	Default destination for Saving messages.
.SH "SEE ALSO"

pico(1), binmail(1), aliases(5), mailaddr(7), sendmail(8), spell(1), imapd(8)

.br
Newsgroup:  comp.mail.pine
.br
Pine Information Center:  http://www.washington.edu/pine
.br
Source distribution:  ftp://ftp.cac.washington.edu/pine/pine.tar.Z
.br
Pine Technical Notes, included in the source distribution.
.br
C-Client messaging API library, included in the source distribution.
.SH ACKNOWLEDGMENTS
.na 
.nf

The University of Washington Pine development team (part of the UW Office 
of Computing & Communications) includes:
 
 Project Leader:           Mike Seibel.
 Principal authors:        Mike Seibel, Steve Hubert, Laurence Lundblade.
 C-Client library & IMAPd: Mark Crispin.
 Pico, the PIne COmposer:  Mike Seibel.
 Bug triage, user support: David Miller.
 Port integration:         David Miller.
 Documentation:            David Miller, Stefan Kramer, Kathryn Sharpe.
 PC-Pine for DOS:          Mike Seibel.
 PC-Pine for Windows:      Tom Unger.
 Project oversight:        Terry Gray.
 Principal Patrons:        Ron Johnson, Mike Bryant.
 Additional support:       NorthWestNet.
 Initial Pine code base:   Elm, by Dave Taylor & USENET Community Trust.
 Initial Pico code base:   MicroEmacs 3.6, by Dave G. Conroy.
 User Interface design:    Inspired by UCLA's "Ben" mailer for MVS.
 Suggestions/fixes/ports:  Folks from all over!

Copyright 1989-1997 by the University of Washington.
Pine and Pico are trademarks of the University of Washington.

97.02.26
