/* XPM */
static char * debug2_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconGray3	m white	c #adadadadadad",
"o	s iconGray5	m black	c #737373737373",
"O	s iconColor7	m white	c cyan",
"+	s iconColor2	m white	c white",
"@	c #104010401040",
"#	s iconGray4	m white	c #949494949494",
"$	s iconColor4	m white	c green",
"%	s iconGray8	m black	c #212121212121",
"&	c #34D334D334D3",
"*	c #596551445555",
"=	c #65959A696595",
"-	c #6185F3CE6185",
";	s iconColor6	m white	c yellow",
":	s iconColor3	m black	c red",
/* pixels */
"                   ..........                   ",
"               ....XXXXo.oXXX....               ",
"             ..XXXXOOOOo.oOOOXXXX..             ",
"           ..XXOOOOOOOOo.oOOOOOOOXX..           ",
"          .XXOOOOOOOOOOo.oOOOOOOOOOXX.          ",
"         .XOOOOOOOOOOOOX.XOOO++OOOOOOX.         ",
"      . OOOOOOOOOOOOOOOX.XOO++++OOOOOOOO  .     ",
"       ...OOOOOOOOOOOOOX.XOO++++++OOOOO...      ",
"      OOOO....OOOOOOOOOX.XOOO++++++....OOO      ",
"     .XOOOOOOO...OOOOOOO.OOOO+++...++OOOOO.     ",
"    .XOOOOOOOOOOO..OOOOO.OOOOO..+++++OOOOOX.    ",
"   .XOOOOOOOOOOOOOO.OOOOOOOOO.OOO+++++OOOOOX.   ",
"   .XOOOOOOOOOOOOOOO..O...O..OOOOO+++++OOOOX.   ",
"  .XOOOO++OOOOOOOOOOOO@#$$.OOOOOOOO++++OOOOOX.  ",
"  .XOOO++OOOOOOOOOOOO%&**%..OOOOOOO+++OOOOOOX.  ",
" .XOOOO++OOOOOOOOOOOO&*X&XX.OOOOOOOO+OOOOOOOOX. ",
" .XOOOO+OOOOOOOOO....**X*XXX....OOOOOOOOOOOOOX. ",
" .XOOO++OOOOOOOO.OOO.XXX=X+$.OOO.OOOOO++++OOOX. ",
" .XOOOOOOOOOOO..OOO.XXX$=X++$.OOO..OOO+++OOOOX. ",
".XOOOOOOOOOOOOOOOOO.*=$$&$-+-.OOOOOOOO+++OOOOOX.",
".XOOOOOOOOOOOOOOOOO.*X$$.$$--.OOOOOOOOOOOOOOOOX.",
".XOOOOOOOOOOOOOOO...XX$+.$$$$...OOOOOOOOOOOOOOX.",
".ooooXXXXOOOOOOO.OO.X$++.$$$$.OO.OOOOOOXXXooooo.",
"..............OO.OO.*$++.X$+*.OO.O..............",
".ooooXXXXOOOOOOO.OO.*XX$&X$+-.OO.OOOOOOXXXooooo.",
".XOOOOOOOOOOOOO.OOO.&*XX&X+X..OOO.OOOOOOO+OOOOX.",
".XOOOOOOOOOOOOO.OOOO.***&XX..OOOO.OOOOOOOOOOOOX.",
".XOOOOOOOOOOOOO.OO..&*&&;..;...OO.OOOOOOO+OOOOX.",
".XOOOOOOOOOOOO.OOO..oo:::::+...OOO.OOOOO++OOOOX.",
" .XOOOOOOOOOO.OOO..Ooo:;;;;+.O..OOO.OOOO++OOOX. ",
" .XOOOOOOOOO.OOOOO.O.oo:;;+:.O.OOOOO.OO+++OOOX. ",
" .XOOOOOOOOOOOOOO..OO.:::::.OO..OOOOOOO++OOOOX. ",
" .XOOOO+OOOOOOOOOO.OOO..&&.OOO.OOOOOOOO++OOOOX. ",
"  .XOOO++OOOOOOOO..OOOOOOOOOOO..OOOOOO++OOOOX.  ",
"  .XOOO+++OOOOOOOO.OOOOO.OOOOO.OOOOOO+++OOOOX.  ",
"   .XOOO++OOOOOOO..OOOOO.OOOOO..OOOOO+++OOOX.   ",
"   .XOOOOOOOOOOOOO.OOOOO.OOOOO.OOOOOOO+OOOOX.   ",
"    .XOOOOOOOOOOO..OOOOO.OOOOO..OOOOOOOOOOX.    ",
"     .XOOOOOOOOOOO.OOOOO.OOOOO.OOOOOOOOOOX.     ",
"      .XOOOOOOOOO.OOOOOX.XOOOOO.OOOOOOOOX.      ",
"      .XXOOOOOOOO.OOOOOX.XOOOOO.OOOOOOOXX.      ",
"       ..XOOOOOO.OOOOOOX.XOOOOOO.OOOOOX..       ",
"         .XOOOOO.OOOOOOX.oOOOOOO.OOOOX.         ",
"          .XXOO.OOOOOOOX.oOOOOOOO.OXX.          ",
"           ..XXOOOOOOOOo.oOOOOOOOXX..           ",
"             ..XXXXOOOOo.oOOOXXXX..             ",
"               ....XXXXo.oXXX....               ",
"                   ..........                   "};
/* ident	"@(#)debugger:libmotif/common/debug.l.pm	1.1" */
