/* XPM */
static char * debug2_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor7	m white	c cyan",
"o	s iconColor2	m white	c white",
"O	c #104010401040",
"+	s iconGray8	m black	c #212121212121",
"@	c #34D334D334D3",
"#	c #596551445555",
"$	s iconGray4	m white	c #949494949494",
"%	s iconColor4	m white	c green",
"&	c #65959A696595",
"*	c #6185C30B8207",
"=	s iconColor3	m black	c red",
"-	s iconColor6	m white	c yellow",
/* pixels */
"             .......            ",
"          ...XXX.XXX...         ",
"        ..XXXXXX.XXXXXX..       ",
"       XXXXXXXXX.XXooXXXXX      ",
"     ..XXXXXXXXX.XXooooXXX..    ",
"     XX...XXXXXX.XXXooo...XX    ",
"    .XXXXX...XXXXXXX...ooXXX.   ",
"   .XXXXXXXXX..XXX..XXooooXXX.  ",
"   .XXXXXXXXXXXO..XXXXXoooXXX.  ",
"  .XXXXXXXXXXX+@.+.XXXXXXXXoXX. ",
"  .XXooXXXX...###$$...XXXXooXX. ",
"  .XXooXX..XX.$%&o%.XX..XXoooX. ",
" .XXoooXXXXXX.&%@oo.XXXXXXoooXX.",
" .XXXXXXXXXXX.$%.%%.XXXXXXXooXX.",
" .XXXXXXXXX...%%.%%...XXXXXXXXX.",
" ........XX.X.%%.%o.X.XX........",
" .XXXXXXXX.XX.#%@*%.XX.XXXXXXXX.",
" .XXXXXXXX.XX.##@...XX.XXXXooXX.",
" .XXXXXXX.XX..====o..XX.XXoooXX.",
" .XXXXXXX.X..X.=--o...X.XXooXXX.",
"  .XXXXXXXXX.X.$==.X.XXXXXooXX. ",
"  .XXXXXXXX..XX.@@XX..XXXooXXX. ",
"  .XXXXXXXXX.XXX.XXX.XXXXooXXX. ",
"   .XXXXXXX..XXXXXXX..XXXXXXX.  ",
"   .XXXXXXXX.XXXXXXX.XXXXXXXX.  ",
"    .XXXXXXX.XXX.XXX.XXXXXXX.   ",
"     .XXXXXX.XXX.XXX.XXXXXX.    ",
"      .XXXX.XXXX.XXXX.XXXX.     ",
"       .XX.XXXXX.XXXXX.XX.      ",
"        ..XXXXXX.XXXXXX..       ",
"          ...XXX.XXX...         ",
"             .......            "};
/* ident	"@(#)debugger:libmotif/common/debug.m.pm	1.1" */
