#ifndef	_WINDOW_SHP_H
#define _WINDOW_SHP_H
#ident	"@(#)debugger:libmotif/common/Window_shP.h	1.2"

// toolkit specific members of the Window_shell class
// included by ../../gui.d/common/Window_sh.h

// toolkit specific members:
// 	busy_count
// 	focus
//	window_widget	primary widget, widget in base class is form widget
// 	msg_widget	label widget for messages in footer
// 	string		text displayed in footer
// 	errors		number of errors generated by last action

#define WINDOW_SHELL_TOOLKIT_SPECIFICS	\
	int		busy_count;	\
	Component	*focus;		\
	Widget		window_widget;	\
	Widget		msg_widget;	\
	Widget		focus_widget;	\
	XmString	blank_str;	\
	char		*string;	\
	int		errors;		

#endif // WINDOW_SHP_H
