#ident	"@(#)OSRcmds:date/date.mk	1.1"
#	@(#) date.mk 25.5 95/02/20 
#
#	      UNIX is a registered trademark of AT&T
#		Portions Copyright 1976-1989 AT&T
#	Portions Copyright 1980-1989 Microsoft Corporation
#    Portions Copyright 1983-1995 The Santa Cruz Operation, Inc
#		      All Rights Reserved
#	Copyright (c) 1984, 1986, 1987, 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.
#
#	Modification History
#
#	scol!markhe		13 July 1992
#	- Added message catalogue support.
#	scol!ianw		12 May 1994
#	- Added -Kold to CFLAGS and LDFLAGS, date needs to be built with
#	  the Tbird libc until the USL libc correctly sets the tm_tzadj
#	  field of the tm structure.
#	scol!ianw		09 Aug 1994
#	- Removed use of -Kold, it is no longer necessary.
#	scol!donaldp		16 Feb 95
#	- Added support for multiple message catalogues.

include $(CMDRULES)
include ../make.inc

#	Makefile for date

INTL=-DINTL

DIR = $(OSRDIR)


# LDFLAGS = -s $(XPGUTIL) ../lib/libcmd.a $(LDLIBS)

CFLAGS = -O -I$(INC)

#top#
# Generated by makefile 1.47

MAKEFILE = date.mk


MAINS = date

OBJECTS =  date.o

SOURCES =  date.c

ALL:		$(MAINS)

date:		date.o
	$(CC) $(CFLAGS)  -o date  date.o $(LDFLAGS)


date.o:		 $(SYSINC)/types.h $(INC)/utmp.h \
		 $(INC)/stdio.h $(INC)/time.h $(SYSINC)/uadmin.h \
		 date_msg.h

date_msg.h:	NLS/en/date.gen
	$(MKCATDEFS) date $? >/dev/null
	cat date_msg.h | sed 's/"date.cat@Unix"/"OSRdate.cat@Unix"/g' > date_msgt.h
	mv date_msgt.h date_msg.h

GLOBALINCS = $(INC)/stdio.h $(SYSINC)/types.h \
	$(INC)/time.h $(INC)/utmp.h


clean:
	rm -f $(OBJECTS) date_msg.h

clobber: clean
	rm -f $(MAINS) $(OBJECTS)
	$(DOCATS) -d NLS $@

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(DOCATS) -d NLS $@
	$(INS) -f $(DIR) date

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
