#!/usr/bin/sh -p
# This was introduced because a program that eventually set the
# real user id to 0 (root) cannot be sent a signal by normal user process 
# using kill due permission problem.

kill $1 $2
