# @(#)src/cmd/vxvm/common/admin/admin.mk	1.1 10/16/96 02:19:37 - 
#ident	"@(#)cmd.vxvm:common/admin/admin.mk	1.1"

# Copyright(C)1996 VERITAS Software Corporation.  ALL RIGHTS RESERVED.
# UNPUBLISHED -- RIGHTS RESERVED UNDER THE COPYRIGHT
# LAWS OF THE UNITED STATES.  USE OF A COPYRIGHT NOTICE
# IS PRECAUTIONARY ONLY AND DOES NOT IMPLY PUBLICATION
# OR DISCLOSURE.
# 
# THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND
# TRADE SECRETS OF VERITAS SOFTWARE.  USE, DISCLOSURE,
# OR REPRODUCTION IS PROHIBITED WITHOUT THE PRIOR
# EXPRESS WRITTEN PERMISSION OF VERITAS SOFTWARE.
# 
#               RESTRICTED RIGHTS LEGEND
# USE, DUPLICATION, OR DISCLOSURE BY THE GOVERNMENT IS
# SUBJECT TO RESTRICTIONS AS SET FORTH IN SUBPARAGRAPH
# (C) (1) (ii) OF THE RIGHTS IN TECHNICAL DATA AND
# COMPUTER SOFTWARE CLAUSE AT DFARS 252.227-7013.
#               VERITAS SOFTWARE
# 1600 PLYMOUTH STREET, MOUNTAIN VIEW, CA 94043

COM_TARGETS = vxdctl \
	vxedit \
	vxiod \
	vxprint \
	vxdisk \
	vxdg \
	vxnotify \
	vxtrace \
	vxstat

COM_SBIN_TARGETS = vxrecover 

COM_VEDIT_OBJS = $(COMMON_DIR)/voledit.o
COM_VEDIT_SRCS = $(COMMON_DIR)/voledit.c
COM_VEDIT_LINT_OBJS = voledit.ln

COM_VPRINT_OBJS = $(COMMON_DIR)/volprint.o
COM_VPRINT_SRCS = $(COMMON_DIR)/volprint.c
COM_VPRINT_LINT_OBJS = volprint.ln

COM_VDISK_OBJS = $(COMMON_DIR)/voldisk.o
COM_VDISK_SRCS = $(COMMON_DIR)/voldisk.c
COM_VDISK_LINT_OBJS = voldisk.ln

COM_VDG_OBJS = $(COMMON_DIR)/voldg.o $(COMMON_DIR)/volpack.o
COM_VDG_SRCS = $(COMMON_DIR)/voldg.c $(COMMON_DIR)/volpack.c
COM_VDG_LINT_OBJS = voldg.ln volpack.ln

COM_VNOTIFY_OBJS = $(COMMON_DIR)/volnotify.o
COM_VNOTIFY_SRCS = $(COMMON_DIR)/volnotify.c
COM_VNOTIFY_LINT_OBJS = volnotify.ln

COM_VDCTL_OBJS = $(COMMON_DIR)/voldctl.o
COM_VDCTL_SRCS = $(COMMON_DIR)/voldctl.c
COM_VDCTL_LINT_OBJS = voldctl.ln

COM_VIOD_OBJS = $(COMMON_DIR)/voliod.o
COM_VIOD_SRCS = $(COMMON_DIR)/voliod.c
COM_VIOD_LINT_OBJS = voliod.ln

COM_VRECOVER_OBJS = $(COMMON_DIR)/volrecover.o
COM_VRECOVER_SRCS = $(COMMON_DIR)/volrecover.c
COM_VRECOVER_LINT_OBJS = volrecover.ln

COM_VTRACE_OBJS = $(COMMON_DIR)/voliotrace.o
COM_VTRACE_SRCS = $(COMMON_DIR)/voliotrace.c
COM_VTRACE_LINT_OBJS = voliotrace.ln

COM_VSTAT_OBJS = $(COMMON_DIR)/volstat.o
COM_VSTAT_SRCS = $(COMMON_DIR)/volstat.c
COM_VSTAT_LINT_OBJS = volstat.ln

COM_LOCALINC =

COM_OBJS = $(COM_VEDIT_OBJS) \
	$(COM_VPRINT_OBJS) \
	$(COM_VDISK_OBJS) \
	$(COM_VDG_OBJS) \
	$(COM_VNOTIFY_OBJS) \
	$(COM_VDCTL_OBJS) \
	$(COM_VIOD_OBJS) \
	$(COM_VRECOVER_OBJS) \
	$(COM_VTRACE_OBJS) \
	$(COM_VSTAT_OBJS)

COM_LINT_OBJS = $(COM_VEDIT_LINT_OBJS) \
	$(COM_VPRINT_LINT_OBJS) \
	$(COM_VDISK_LINT_OBJS) \
	$(COM_VDG_LINT_OBJS) \
	$(COM_VNOTIFY_LINT_OBJS) \
	$(COM_VDCTL_LINT_OBJS) \
	$(COM_VIOD_LINT_OBJS) \
	$(COM_VRECOVER_LINT_OBJS) \
	$(COM_VTRACE_LINT_OBJS) \
	$(COM_VSTAT_LINT_OBJS)


COM_SRCS = $(COM_VEDIT_SRCS) \
	$(COM_VPRINT_SRCS) \
	$(COM_VDISK_SRCS) \
	$(COM_VDG_SRCS) \
	$(COM_VNOTIFY_SRCS) \
	$(COM_VDCTL_SRCS) \
	$(COM_VIOD_SRCS) \
	$(COM_VRECOVER_SRCS) \
	$(COM_VTRACE_SRCS) \
	$(COM_VSTAT_SRCS)


