$ @(#)audioconfig.osa.msg	7.1	97/10/22

$moduleset SCO_AUDIOCONFIGOSA tcl=audioconfig.osa

$ Message catalog for SCOadmin audio configuration osa: audioconfig.osa

$ Errors
SCO_AUDIOCONFIGOSA_ERR_NO_MODEL_LIST	"Unable to get model list for %s."
SCO_AUDIOCONFIGOSA_ERR_NO_AUDINFO	"Unable to open audinfo file: %s."
SCO_AUDIOCONFIGOSA_ERR_MISSING_ATTR	"Missing attribute: %1$s, in function: %2$s."
SCO_AUDIOCONFIGOSA_ERR_UNIT_EXISTS	"Unable to create audiocard.  Unit: %s already exists."
SCO_AUDIOCONFIGOSA_ERR_IDBUILD		"Error in idbuild: %s"
SCO_AUDIOCONFIGOSA_ERR_IDINSTALL	"Error in idinstall: %s"
SCO_AUDIOCONFIGOSA_ERR_MODADMIN		"Error in modadmin: %s"
SCO_AUDIOCONFIGOSA_ERR_OPEN_DEV_AUDIO	"Error in opening /dev/audio"

