#ident	"@(#)OSRcmds:cmos/cmos.mk	1.1"
#	@(#) cmos.mk 1.2 89/08/06 
#
#	      UNIX is a registered trademark of AT&T
#		Portions Copyright 1976-1989 AT&T
#	Portions Copyright 1980-1989 Microsoft Corporation
#    Portions Copyright 1983-1989 The Santa Cruz Operation, Inc
#		      All Rights Reserved
#
#	Copyright (c) 1984, 1986, 1987, 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

include $(CMDRULES)
include ../make.inc

#	Makefile for cmos

DIR = $(OSRDIR)

LFLAGS = $(IFLAG) $(LDLIBS) 

CFLAGS = -O -I$(INC)

#top#
# Generated by makefile 1.47

MAKEFILE = cmos.mk


MAINS = cmos

OBJECTS =  cmos.o

SOURCES =  cmos.c

ALL:		$(MAINS)

cmos:		cmos.o 
	$(CC) $(CFLAGS)  -o cmos  cmos.o  $(LDFLAGS) $(LFLAGS)


cmos.o:	 $(INC)/stdio.h $(INC)/ctype.h $(INC)/fcntl.h

GLOBALINCS = $(INC)/stdio.h $(INC)/ctype.h $(INC)/fcntl.h

clean:
	rm -f $(OBJECTS)

clobber: clean
	rm -f $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(DIR) cmos

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
